import {
  Award,
  BadgeCheck,
  BriefcaseBusiness,
  Code2,
  FileText,
  FolderGit,
  GraduationCap,
  LayoutDashboard,
  Palette,
  Route,
  ScanSearch,
  Sparkles,
  Target,
  UserCheck,
} from "lucide-react";

export const locales = ["en", "fr"] as const;
export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export const localeMeta: Record<Locale, { label: string; name: string; dir: Direction }> = {
  en: { label: "EN", name: "English", dir: "ltr" },
  fr: { label: "FR", name: "Français", dir: "ltr" },
};

export const futureLocaleMeta = {
  ar: { label: "AR", name: "Arabic", dir: "rtl" as Direction },
};

export const templateIds = [
  "minimal-executive",
  "dark-tech",
  "creative-grid",
  "story-journey",
  "recruiter-focus",
  "developer-signature",
  "career-chronicle",
] as const;

export type TemplateId = (typeof templateIds)[number];

export const templateMeta: Record<
  TemplateId,
  {
    icon: typeof BriefcaseBusiness;
    className: string;
    accent: string;
    previewClass: string;
  }
> = {
  "minimal-executive": {
    icon: BriefcaseBusiness,
    className: "template-minimal",
    accent: "#315dff",
    previewClass: "bg-[#f8f4ed] text-[#172033]",
  },
  "dark-tech": {
    icon: Code2,
    className: "template-dark",
    accent: "#4da3ff",
    previewClass: "bg-[#071021] text-white",
  },
  "creative-grid": {
    icon: Palette,
    className: "template-creative",
    accent: "#ff7a66",
    previewClass: "bg-[#fff8ed] text-[#151926]",
  },
  "story-journey": {
    icon: Route,
    className: "template-story",
    accent: "#67e8a5",
    previewClass: "bg-[#141014] text-[#fff9f2]",
  },
  "recruiter-focus": {
    icon: UserCheck,
    className: "template-recruiter",
    accent: "#0f766e",
    previewClass: "bg-[#f7f9fc] text-[#172033]",
  },
  "developer-signature": {
    icon: FolderGit,
    className: "template-developer",
    accent: "#00d5ff",
    previewClass: "bg-[#040813] text-white",
  },
  "career-chronicle": {
    icon: FileText,
    className: "template-chronicle",
    accent: "#6c7cff",
    previewClass: "bg-[#f4f7fb] text-[#172033]",
  },
};

export const icons = {
  award: Award,
  badge: BadgeCheck,
  briefcase: BriefcaseBusiness,
  code: Code2,
  file: FileText,
  github: FolderGit,
  graduate: GraduationCap,
  dashboard: LayoutDashboard,
  scan: ScanSearch,
  sparkles: Sparkles,
  target: Target,
};

export const copy = {
  en: {
    nav: {
      home: "Home",
      product: "Product",
      demo: "Live demo",
      templates: "Templates",
      pricing: "Plans",
      editor: "Editor",
      create: "Start with your evidence",
      startShort: "Start",
      startLabel: "Start with your evidence",
      language: "Language",
      primary: "Primary navigation",
      menu: "Menu",
      openMenu: "Open navigation menu",
      closeMenu: "Close navigation menu",
      skip: "Skip to main content",
    },
    common: {
      preview: "Preview template",
      useTemplate: "Use this template",
      create: "Start with your evidence",
      demo: "Explore a live demo",
      openEditor: "Open editor",
      viewTemplates: "View templates",
      proof: "Verified proof",
      draft: "Draft",
      published: "Published",
      score: "Readiness score",
      hosted: "Hosted portfolio",
      contact: "Contact",
      downloadCv: "Download CV preview",
      viewProof: "View proof",
      close: "Close",
      all: "All",
      section: "Section",
    },
    hero: {
      eyebrow: "PORTFOLIOS BUILT FROM REAL EVIDENCE",
      title: "ProofFolio AI",
      emphasis: "Turn your projects\ninto proof that opens doors.",
      value:
        "ProofFolio AI brings together your CV, GitHub and certificates to create a professional, verifiable portfolio that you validate before it goes public.",
      trust: ["Bilingual", "Controlled by you", "Hosted", "Shareable"],
      highlights: ["Source-backed", "User-validated", "Recruiter-ready"],
      pipeline: ["CV", "GitHub", "Certificates", "AI proposals", "Published portfolio"],
      mockupTitle: "Recruiter-ready snapshot",
      mockupSubtitle: "AI/data student · product-minded builder",
      cards: [
        { label: "CV", value: "Imported and structured", icon: "file" },
        { label: "GitHub", value: "Projects linked to proof", icon: "github" },
        { label: "Certificates", value: "Evidence attached", icon: "award" },
      ],
    },
    productStage: {
      principle: "AI proposes. You validate. Recruiters trust the proof.",
      tabs: ["Portfolio", "Evidence", "Recruiter"],
      portfolio: {
        label: "Portfolio view",
        title: "Maya Chen",
        subtitle: "Frontend Engineer · AI/Data Products",
        availability: "Available for internships and junior roles",
        stack: ["React", "Next.js", "Python", "Data UX"],
        certificates: "4 certificates attached",
      },
      evidence: {
        label: "Evidence view",
        title: "Approved evidence queue",
        sources: ["GitHub repositories", "CV extraction", "Certificates", "Proof links"],
        status: "User approved",
        repository: "38 repositories mapped",
      },
      recruiter: {
        label: "Recruiter view",
        title: "60-second recruiter snapshot",
        target: "Target role",
        cv: "Download CV simulation",
        contact: "Contact candidate",
      },
    },
    heroPreview: {
      readinessTitle: "Portfolio readiness",
      readinessChecks: ["CV imported", "GitHub projects linked", "Certificates attached"],
      aiSuggestions: "3 AI suggestions awaiting approval",
      githubActivity: "GitHub activity",
      certificates: "Certificates",
      validationQueue: "Validation queue",
    },
    importEvidence: {
      kicker: "Import your evidence",
      title: "Start with sources recruiters can actually trust.",
      body:
        "ProofFolio is designed around source-backed material: CV details, GitHub repositories, certificates, LinkedIn context and manual achievements.",
      sources: [
        { name: "Upload CV", detail: "Turn a static resume into structured profile evidence.", icon: "file" },
        { name: "Connect GitHub", detail: "Map repositories to proof-of-work project cards.", icon: "github" },
        { name: "Add LinkedIn", detail: "Use professional context without publishing blindly.", icon: "briefcase" },
        { name: "Upload certificates", detail: "Attach proof directly to skills and projects.", icon: "award" },
        { name: "Add manually", detail: "Keep control over achievements, roles and highlights.", icon: "target" },
      ],
    },
    evidenceBoard: {
      queueTitle: "Evidence queue",
      columns: ["Source", "Proposal", "Validation"],
      metrics: ["items imported", "AI suggestions", "ready approvals"],
    },
    workflow: {
      kicker: "How ProofFolio works",
      title: "A validation workflow, not an autopilot portfolio.",
      body:
        "The platform is built around a clear loop: import evidence, let AI structure it, review every suggestion, then publish intentionally.",
      steps: [
        { number: "01", title: "Import your sources", detail: "CV, GitHub, certificates, LinkedIn context and manual proof enter one workspace." },
        { number: "02", title: "AI structures your work", detail: "Projects, skills, certificates and career signals become editable proposals." },
        { number: "03", title: "You validate each suggestion", detail: "Nothing is published silently. You approve, edit or reject every generated item." },
        { number: "04", title: "Publish your portfolio", detail: "Launch a source-backed portfolio URL with recruiter-ready summaries and evidence." },
      ],
    },
    transformation: {
      kicker: "Transformation demo",
      title: "From scattered proof to a coherent professional presence.",
      body:
        "ProofFolio turns disconnected career material into a structured portfolio story with evidence, clarity and hiring context.",
      beforeTitle: "Before",
      afterTitle: "After",
      before: ["Plain CV document", "Disconnected GitHub repositories", "Unstructured certificates", "Generic student profile"],
      after: ["Premium hosted portfolio", "Proof-of-work cards", "Readiness score", "Recruiter snapshot", "Explainable AI insights"],
    },
    intelligence: {
      kicker: "AI intelligence visualization",
      title: "AI proposes. The user decides what becomes public.",
      body:
        "The demo shows simulated AI analysis panels, review states and approval checkpoints without claiming production AI services.",
      inputTitle: "Input",
      outputTitle: "AI proposal",
      reviewTitle: "User review",
      inputs: ["CV text", "GitHub README", "Skills", "Certificates", "Project evidence"],
      outputs: ["Skill map", "Readiness score", "Career evolution", "Project descriptions", "Template recommendation"],
      labels: ["Evidence", "Signal strength", "Narrative", "Recommendation"],
      approvals: ["Review proposal", "Edit language", "Approve for portfolio"],
    },
    platform: {
      kicker: "Product workflow",
      title: "The visible demo mirrors the future product system.",
      body:
        "Aya's product logic is represented as an approval-based journey from account setup to public portfolio, analytics and recruiter contact.",
      stages: [
        { name: "Account and onboarding", detail: "Choose a profile goal, confirm language and start with a draft workspace." },
        { name: "Connect evidence", detail: "Import CV content, GitHub repositories and certificates into one review queue." },
        { name: "AI proposals", detail: "ProofFolio suggests summaries, skill signals and project stories for user approval." },
        { name: "Customize and preview", detail: "Select a template, tune typography, switch desktop/mobile previews and publish intentionally." },
        { name: "Recruiter and analytics", detail: "Share a public URL, track interest and keep notifications visible in the product loop." },
      ],
    },
    templateShowcase: {
      kicker: "Template showcase",
      title: "Seven templates, seven different professional stories.",
      body:
        "Each template changes layout rhythm, typography, motion and mood so the portfolio fits the candidate rather than forcing everyone into one skin.",
      directions: [
        { name: "Developer", detail: "Proof-heavy portfolios for builders, repositories and shipped systems.", template: "developer-signature" },
        { name: "Data / AI", detail: "Structured evidence for models, notebooks, dashboards and learning curves.", template: "career-chronicle" },
        { name: "Creative", detail: "Visual case studies for interface designers and creative technologists.", template: "creative-grid" },
      ],
    },
    proof: {
      kicker: "Proof, not promises",
      title: "Every strong claim needs a visible source.",
      body:
        "ProofFolio makes the trust layer visible: GitHub-linked projects, verified certificates, user-approved AI content and source-backed portfolio elements.",
      stats: [
        ["12", "projects analyzed"],
        ["6", "verified certificates"],
        ["4", "career themes"],
        ["91", "portfolio score"],
      ],
      projects: [
        { name: "Atlas UI Systems", signal: "Design system · 18 reusable components", proof: "Storybook, accessibility notes, release changelog" },
        { name: "ModelOps Notes", signal: "AI workflow · local inference prototype", proof: "README, benchmark table, demo screenshots" },
        { name: "Campus Connect", signal: "Full-stack product · student services", proof: "API docs, deployment log, testing notes" },
      ],
    },
    career: {
      kicker: "Career evolution",
      title: "A living timeline shows where the profile is growing.",
      body:
        "The product demo maps skill momentum over time and turns it into a practical next-step recommendation.",
      skills: [
        ["Frontend", "92"],
        ["Backend", "76"],
        ["AI", "68"],
        ["Cloud", "63"],
        ["Data", "58"],
      ],
      recommendation:
        "Recommended focus: publish two AI-assisted interface case studies and add deployment evidence for the cloud track.",
    },
    recruiter: {
      kicker: "Recruiter snapshot",
      title: "A focused view for fast evaluation.",
      summary:
        "Candidate with strong product UI craft, credible implementation evidence and a clear AI tooling direction.",
      target: "Target role",
      role: "Frontend Engineer · AI Product Interfaces",
      availability: "Available for internships and junior roles",
      skills: ["React", "Design systems", "TypeScript", "AI workflows", "Accessibility"],
      contact: "Contact candidate",
    },
    plans: {
      kicker: "Pricing preview",
      title: "Clear plans for every stage of the portfolio journey.",
      body:
        "The model stays simple: explore for free, grow as a student, or unlock the complete professional presence.",
      monthly: "Monthly",
      yearly: "Yearly",
      billingLabel: "Billing period",
      tableTitle: "Feature comparison",
      feature: "Feature",
      disclaimer: "Pricing is a product preview. Payments and billing are not enabled in this demo.",
      tiers: [
        {
          id: "free",
          name: "Free",
          monthlyPrice: "$0",
          yearlyPrice: "$0",
          description: "Explore the essentials and publish your first portfolio.",
          cta: "Start free",
        },
        {
          id: "student",
          name: "Student",
          monthlyPrice: "$5 / month",
          yearlyPrice: "$48 / year",
          badge: "Most popular",
          description: "Build a stronger profile for internships, PFE, and early career opportunities.",
          cta: "Choose Student",
        },
        {
          id: "vip",
          name: "VIP",
          monthlyPrice: "$12 / month",
          yearlyPrice: "$108 / year",
          badge: "Full professional presence",
          description: "For ambitious creators and professionals who want the complete ProofFolio experience.",
          cta: "Explore VIP",
        },
      ],
      comparison: [
        ["Templates", "1", "3", "7"],
        ["Projects", "3", "10", "Unlimited"],
        ["Public portfolio URL", "Included", "Included", "Included"],
        ["GitHub import", "Manual only", "Basic sync", "Full sync"],
        ["GitHub auto-updates", "Not included", "Limited", "Included"],
        ["CV analysis", "Basic", "Full", "Full + profile evolution comparison"],
        ["Certificates", "2", "10", "Unlimited"],
        ["Colors and fonts", "Limited", "Advanced", "Full customization"],
        ["Portfolio analytics", "Not included", "Basic", "Full"],
        ["Career insights", "Basic", "Full", "Advanced"],
        ["Remove ProofFolio branding", "Not included", "Not included", "Included"],
        ["Custom domain", "Not included", "Not included", "VIP feature coming soon"],
        ["Recruiter Focus template", "Not included", "Not included", "Included"],
        ["Developer Signature template", "Not included", "Student preview", "Included"],
        ["Career Chronicle template", "Not included", "Not included", "Included"],
      ],
    },
    finalCta: {
      title: "Your next portfolio should not just look good.",
      body: "It should prove what you can do, with sources recruiters can understand quickly.",
      cta: "Start with your evidence",
    },
    footer: {
      product: "Product demo",
      templates: "Templates",
      note:
        "ProofFolio AI now includes a V3 Supabase foundation for auth, private evidence uploads and manual projects. AI, GitHub import, publishing and payments remain deferred.",
    },
    demo: {
      kicker: "Live product demo",
      title: "A complete sample portfolio generated from realistic student evidence.",
      body:
        "This route shows how the dashboard, readiness score and public portfolio preview work together while V3 onboarding handles real evidence intake separately.",
      tabs: ["Portfolio", "Evidence", "Readiness"],
      candidate: "Maya Chen",
      headline: "Product-minded frontend engineer building AI-assisted learning tools.",
      location: "Paris · Remote friendly",
      highlights: ["Shipped 4 polished demos", "Maintains an accessibility checklist", "Documents product decisions clearly"],
    },
    editor: {
      kicker: "Portfolio editor",
      title: "Shape the saved portfolio draft behind the preview.",
      body: "Your owned draft, approved proof and design preferences stay connected in one private workspace.",
      workspaceTitle: "Build the portfolio from evidence-ready content.",
      workspaceBody: "Edit the identity, approved projects, proof structure and visual system without turning private files into public links.",
      status: "Saved to workspace",
      evidenceReady: "Evidence-ready draft",
      approvedEvidence: "approved evidence items",
      portfolioId: "Portfolio ID",
      publishState: "Private draft only",
      undo: "Undo",
      redo: "Redo",
      mobilePreview: "Mobile preview",
      desktopPreview: "Desktop preview",
      persistence: {
        ready: "Private workspace connected",
        readyBody: "Changes are saved to your user-owned portfolio draft in Supabase.",
        preview: "Preview workspace",
        previewBody: "No saved portfolio is loaded. Changes remain visual and are not presented as backend persistence.",
      },
      unavailable: {
        setup_required: {
          title: "Portfolio persistence is not configured.",
          body: "This portfolio ID cannot be loaded until the Supabase environment and editor migration are available.",
        },
        denied: {
          title: "This portfolio is not available.",
          body: "The draft does not exist or belongs to another account. ProofFolio does not expose ownership details.",
        },
        error: {
          title: "The editor workspace could not load.",
          body: "Confirm that the persistent editor migration is applied, then return from the evidence onboarding handoff.",
        },
      },
      panels: {
        identity: "Identity",
        projects: "Projects",
        evidence: "Evidence and certificates",
        structure: "Portfolio structure",
        appearance: "Appearance",
        motion: "Advanced motion",
      },
      panelDescriptions: {
        identity: "Portfolio title and professional headline",
        projects: "Approved manual projects and proof links",
        evidence: "Private source records and review state",
        structure: "Section visibility and reading order",
        appearance: "Template, color, typography and density",
        motion: "Accessible preview movement",
      },
      fields: {
        portfolioTitle: "Portfolio title",
        headline: "Professional headline",
        projectTitle: "Project title",
        summary: "Project summary",
        technologies: "Technologies",
        repositoryUrl: "Repository URL",
        liveDemoUrl: "Live demo URL",
      },
      saveStates: {
        preview: "Preview only",
        unsaved: "Unsaved changes",
        saving: "Saving...",
        saved: "Saved",
        failed: "Save failed",
      },
      actions: {
        saveNow: "Save now",
        saveProject: "Save project",
        moveUp: "Move up",
        moveDown: "Move down",
        returnToOnboarding: "Return to evidence onboarding",
      },
      recovery: {
        title: "Unsaved local text found",
        body: "A local recovery buffer contains text from this portfolio that was not confirmed by the server.",
        restore: "Restore text",
        dismiss: "Dismiss recovery",
      },
      evidence: {
        privateNotice: "Evidence files remain private. This workspace shows filenames and source metadata, never an unauthenticated Storage URL.",
        approved: "Approved for preview",
        privateOnly: "Private source only",
      },
      structure: {
        sections: {
          projects: "Projects",
          evidence: "Evidence",
          certificates: "Certificates",
        },
      },
      sourceBadges: {
        cv: "CV",
        certificate: "Certificate",
        manualProject: "Manual project",
        github: "GitHub - coming soon",
      },
      preview: {
        label: "Portfolio preview",
        viewport: "Preview viewport",
        privateDraft: "Private draft preview",
        structureLabel: "Portfolio sections",
        headlineFallback: "Add a professional headline in Identity.",
        projectsTitle: "Selected work",
        evidenceTitle: "Evidence-backed profile",
        certificatesTitle: "Certificates",
        noApprovedProjects: "No approved project is ready for the preview.",
        noApprovedEvidence: "No approved source is ready for this section.",
        approvedOnly: "Approved evidence only",
        approvedSources: "approved sources",
        projectCount: "projects",
        repository: "Repository",
        liveDemo: "Live demo",
      },
      emptyStates: {
        projectsTitle: "No approved projects yet",
        projectsBody: "Approve a manual project suggestion before editing it as portfolio-ready content.",
        evidenceTitle: "No evidence records yet",
        evidenceBody: "Add a private CV, certificate or manual project in the evidence workspace.",
      },
      controls: {
        template: "Template",
        color: "Accent color",
        typography: "Typography",
        layout: "Layout",
        projects: "Project display",
        spacing: "Spacing",
        animation: "Animation level",
      },
      options: {
        typography: ["Editorial", "Technical", "Compact"],
        layout: ["Narrative", "Grid", "Snapshot"],
        projects: ["Case studies", "Evidence cards", "Repository feed"],
        spacing: ["Compact", "Balanced", "Airy"],
        animation: ["Reduced", "Refined", "Expressive"],
      },
      empty: "No project selected",
      loading: "Refreshing preview",
    },
    auth: {
      kicker: "Evidence-first access",
      signInTitle: "Return to your proof workspace.",
      signInBody: "Sign in to continue the saved onboarding flow, review evidence and prepare an editor draft.",
      signUpTitle: "Create the account that owns your evidence.",
      signUpBody: "Start with a private portfolio draft, then add CV files, certificates and manual projects.",
      formTitle: "Secure portfolio access",
      email: "Email address",
      emailPlaceholder: "you@example.com",
      password: "Password",
      passwordPlaceholder: "At least 6 characters",
      signInAction: "Sign in",
      signUpAction: "Create account",
      signOut: "Sign out",
      loading: "Checking access...",
      needAccount: "New to ProofFolio?",
      haveAccount: "Already have an account?",
      createAccount: "Create an account",
      backToSignIn: "Sign in instead",
      proofPoints: ["Private evidence storage", "User-owned drafts", "No fake AI claims"],
    },
    onboarding: {
      workspace: "Evidence workspace",
      kicker: "Guided proof-building workspace",
      title: "Start from evidence, then shape the portfolio.",
      body:
        "This V3 foundation stores real portfolio drafts, uploads and manual project evidence before handing a selected template to the editor.",
      resumeTitle: "Resume your evidence draft",
      resumeBody: "A saved draft is waiting with private evidence, review decisions and template progress.",
      resumeDraft: "Resume draft",
      startNewDraft: "Start a new draft",
      progressTitle: "Draft progress",
      progress: {
        sourcesAdded: "Sources added",
        uploadsCompleted: "Uploads completed",
        projectsAdded: "Projects added",
        suggestionsApproved: "Suggestions approved",
        templateSelected: "Template selected",
      },
      progressStates: {
        done: "Done",
        pending: "Pending",
      },
      stepEyebrow: "Step 1",
      uploadEyebrow: "Evidence intake",
      reviewEyebrow: "Prototype review",
      templateEyebrow: "Template recommendation",
      summaryEyebrow: "Editor handoff",
      steps: {
        sources: { label: "Sources", detail: "Choose where proof will come from." },
        upload: { label: "Evidence", detail: "Upload PDFs or add a manual project." },
        review: { label: "Review", detail: "Approve, edit or reject prototype suggestions." },
        template: { label: "Template", detail: "Select the right portfolio experience." },
        summary: { label: "Handoff", detail: "Open the evidence-ready editor draft." },
      },
      connectedStatus: "Protected persistence active",
      connectedDetail: "Your portfolio draft, evidence and review decisions are saved to Supabase.",
      previewStatus: "Persistence blocked",
      persistenceBlocked: "Sign in with Supabase configured to save evidence. This local preview does not create a connected account.",
      persistenceDisabled: "Persistence disabled",
      honestyNotice: "Your uploads stay private. Automated CV analysis and GitHub import are coming next.",
      sourcesTitle: "Select the evidence sources for this portfolio.",
      sourcesBody: "Choose what you want to add first. GitHub is visible as a future integration, but not active in this sprint.",
      sources: {
        cv: "CV",
        cvDetail: "Upload a private PDF CV without claiming automated parsing.",
        certificate: "Certificates",
        certificateDetail: "Store proof documents privately and attach them to your draft.",
        manualProject: "Manual Project",
        manualDetail: "Describe a real project, stack and proof links yourself.",
        github: "GitHub - Coming soon",
        githubDetail: "Repository import is deferred; no OAuth is implemented yet.",
      },
      comingSoon: "Coming soon",
      saved: "saved",
      ready: "Ready",
      sourceStates: {
        notAdded: "Not added",
        uploading: "Uploading",
        savedPrivately: "Saved privately",
        needsAttention: "Needs attention",
      },
      uploadTitle: "Add the proof material.",
      uploadBody: "PDF files go to private storage. Manual projects are saved as evidence and project drafts.",
      uploadCv: "Upload CV",
      uploadCvDetail: "PDF only. The file is stored privately and is not parsed yet.",
      uploadCertificate: "Upload certificate",
      uploadCertificateDetail: "Attach a PDF certificate to the private evidence bucket.",
      githubDeferred: "GitHub import, OAuth and repository analysis are intentionally deferred.",
      manualProjectTitle: "Add manual project",
      manualProjectBody: "Write the project evidence yourself so the first portfolio draft stays honest.",
      saveManualProject: "Save manual project",
      savedEvidence: "Saved evidence",
      noEvidence: "No saved evidence yet.",
      evidenceListTitle: "Private evidence vault",
      removeEvidence: "Remove evidence",
      confirmRemoval: "Confirm removal",
      confirmRemoveBody: "This removes the saved evidence and invalidates linked prototype suggestions for this draft.",
      removeNow: "Remove now",
      fields: {
        projectTitle: "Project title",
        summary: "Short summary",
        technologies: "Technologies",
        repositoryUrl: "Repository URL",
        liveDemoUrl: "Live demo URL",
        proposalTitle: "Proposal title",
        proposalSummary: "Proposal summary",
      },
      placeholders: {
        projectTitle: "Atlas UI Systems",
        summary: "What you built, why it matters and what proof exists.",
        technologies: "React, TypeScript, Supabase",
      },
      validation: {
        projectTitle: "Add a project title before saving.",
        projectSummary: "Add a short summary before saving.",
      },
      reviewTitle: "Review prototype draft suggestions.",
      reviewBody:
        "These deterministic suggestions come from saved evidence titles and manual project data. They are not AI analysis.",
      prototypeLabel: "Prototype draft suggestion",
      proofContext: "Proof context",
      evidenceBacked: "Evidence-backed because this suggestion is tied to saved proof in your private draft.",
      activeSuggestions: "Review queue",
      rejectedAuditTitle: "Rejected audit",
      rejectedAuditBody: "Rejected suggestions stay here for traceability and are excluded from the portfolio summary.",
      editSuggestion: "Edit suggestion",
      approvedEvidence: "Approved evidence",
      noSuggestions: "Add evidence first to generate prototype draft suggestions.",
      approve: "Approve",
      edit: "Edit",
      reject: "Reject",
      saving: "Saving...",
      reviewStates: {
        pending: "Pending",
        approved: "Approved",
        edited: "Edited",
        rejected: "Rejected",
      },
      sourceBadges: {
        cv: "CV",
        certificate: "Certificate",
        manualProject: "Manual project",
        github: "GitHub - coming soon",
      },
      templateTitle: "Choose the portfolio experience.",
      templateBody: "ProofFolio recommends exactly three templates for this first evidence-ready handoff.",
      templateReasons: {
        "developer-signature": "Best for technical projects, visible stack and proof-of-work storytelling.",
        "dark-tech": "Best when the evidence leans toward AI, data, systems or a high-signal technical mood.",
        "recruiter-focus": "Best for concise professional evidence and fast hiring review.",
      },
      selected: "Selected",
      templateSelectedStatus: "Template selected",
      summaryTitle: "Your evidence-ready draft is prepared.",
      summaryBody: "The editor receives the real portfolio ID, selected template and review status without claiming publishing exists.",
      portfolioDraft: "Portfolio draft",
      editorReadyTitle: "Evidence-ready draft",
      editorReadyBody: "Open the editor with the saved template and approved evidence count.",
      continueEditor: "Continue to editor",
      openPreviewEditor: "Open preview editor",
      back: "Back",
      next: "Next",
    },
    portfolio: {
      name: "Maya Chen",
      initials: "MC",
      headline: "AI/data student building accessible product interfaces and evidence-rich learning tools.",
      role: "AI Product Interface Developer",
      targetRole: "Frontend Engineer · AI/Data Products",
      location: "Paris · Remote friendly",
      availability: "Available for PFE, internships and junior product engineering roles",
      email: "maya.chen.demo@prooffolio.local",
      summary:
        "A fictional portfolio profile for ProofFolio demos: strong React craft, data storytelling instincts, and a habit of documenting proof behind each project.",
      metrics: [
        ["91", "Readiness"],
        ["38", "Repos mapped"],
        ["6", "Certificates"],
        ["12", "Projects"],
      ],
      projects: [
        {
          name: "Atlas UI Systems",
          category: "Frontend",
          signal: "Design system · 18 reusable components",
          proof: "Storybook coverage, accessibility notes, release changelog",
          impact: "+42% faster prototype handoff",
          detail: "Built a token-led component library for student SaaS products with keyboard states and responsive patterns.",
        },
        {
          name: "ModelOps Notes",
          category: "AI",
          signal: "Local AI workflow · model comparison dashboard",
          proof: "README, benchmark table, evaluation screenshots",
          impact: "6 model runs documented",
          detail: "Created a local-first experiment notebook that explains prompts, latency and output quality for student projects.",
        },
        {
          name: "Campus Connect",
          category: "Full-stack",
          signal: "Student services platform · API + dashboard",
          proof: "API docs, deployment log, test plan",
          impact: "4 core workflows shipped",
          detail: "Designed and implemented a campus services flow with role-aware dashboards and clean issue reporting.",
        },
        {
          name: "Insight Lens",
          category: "Data",
          signal: "Analytics story · portfolio readiness trends",
          proof: "Chart specs, data dictionary, QA notes",
          impact: "9 career signals visualized",
          detail: "Mapped project, certificate and skill growth into a readable readiness graph for profile improvement.",
        },
      ],
      skills: [
        ["React", "92"],
        ["TypeScript", "86"],
        ["Next.js", "82"],
        ["Python", "74"],
        ["Data UX", "79"],
        ["Accessibility", "88"],
      ],
      certificates: ["Google UX Foundations", "Meta Front-End Developer", "IBM Data Fundamentals", "Scrimba React Advanced"],
      timeline: [
        {
          chapter: "Foundations",
          date: "2023",
          title: "Built the first reliable frontend base",
          detail: "Moved from isolated UI exercises to documented React interfaces with accessibility checklists.",
          learned: "Readable components, keyboard states and design tokens make portfolio proof easier to trust.",
        },
        {
          chapter: "First Projects",
          date: "2024",
          title: "Shipped student-facing product demos",
          detail: "Turned campus workflows into full-stack prototypes with API documentation and deployment notes.",
          learned: "Recruiters understand projects faster when outcomes and proof sit next to the code links.",
        },
        {
          chapter: "AI Transition",
          date: "2025",
          title: "Added AI and data storytelling",
          detail: "Started pairing interface craft with local AI experiments, benchmarks and explainable decisions.",
          learned: "AI output needs user approval, editing and traceable evidence before it belongs in a public profile.",
        },
        {
          chapter: "Current Focus",
          date: "2026",
          title: "Positioning for AI product engineering",
          detail: "Refining case studies around product thinking, interface quality and measurable proof-of-work.",
          learned: "A living portfolio should show growth, not just a static list of past work.",
        },
      ],
      scanSteps: ["Fit summary", "Proof quality", "Top projects", "Skill match", "Contact path"],
      filters: ["All", "Frontend", "AI", "Full-stack", "Data"],
    },
    templates: {
      "minimal-executive": {
        name: "Minimal Executive",
        tag: "Elegant, calm, senior-facing.",
        motion: "Nearly static reveals, refined hover states and understated section transitions.",
        profile: "A precise portfolio for business-oriented technical candidates.",
      },
      "dark-tech": {
        name: "Dark Tech",
        tag: "Depth, blue lighting, developer energy.",
        motion: "Ambient depth, interactive project cards and GitHub activity rhythm.",
        profile: "A premium technical portfolio for builders with strong implementation evidence.",
      },
      "creative-grid": {
        name: "Creative Grid",
        tag: "Visual, modular, still professional.",
        motion: "Smooth gallery movement, project expansion and image-led rhythm.",
        profile: "A design-forward portfolio for creative technologists and interface designers.",
      },
      "story-journey": {
        name: "Story Journey",
        tag: "Career narrative with momentum.",
        motion: "Scroll-linked milestones, progressive reveals and timeline emphasis.",
        profile: "A storytelling portfolio for candidates changing levels, domains or roles.",
      },
      "recruiter-focus": {
        name: "Recruiter Focus",
        tag: "Fast scanning, high clarity.",
        motion: "Restrained scoring, clear actions and quick evidence access.",
        profile: "A concise portfolio for recruiters who need fit, proof and contact paths quickly.",
      },
      "developer-signature": {
        name: "Developer Signature",
        tag: "Technical identity with serious proof.",
        motion: "Typewriter roles, filtered project motion, hover depth and toolkit clustering.",
        profile: "A developer-first portfolio for AI engineers, full-stack builders and data creators.",
      },
      "career-chronicle": {
        name: "Career Chronicle",
        tag: "A premium chronological career story.",
        motion: "Scroll-reactive chapters, project detail modal and measured toolkit progress.",
        profile: "A career narrative for students and junior professionals who need to explain growth credibly.",
      },
    },
    templateUi: {
      nav: {
        intro: "Intro",
        projects: "Projects",
        skills: "Skills",
        evidence: "Evidence",
        contact: "Contact",
        proof: "Proof",
        signals: "Signals",
        gallery: "Gallery",
        process: "Process",
        timeline: "Timeline",
        growth: "Growth",
        summary: "Summary",
        scan: "Scan",
        cv: "CV",
        home: "Home",
        work: "Work",
        toolkit: "Toolkit",
        journey: "Journey",
        proofLab: "Proof lab",
        portrait: "Portrait",
        chronology: "Chronology",
        chapters: "Chapters",
      },
      minimal: {
        selectedWork: "Selected work",
        skillSignal: "Skill signal",
      },
      dark: {
        flagship: "Dark Tech flagship",
        roles: ["AI Engineer", "Full-Stack Developer", "Data Builder"],
        assurance: ["Evidence locked", "AI reviewed", "User approved"],
        activity: "Live-looking activity",
        command: "$ proofolio scan --evidence --approval-required",
        signals: ["Repositories", "Shipped projects", "Commits", "Certificates", "Profile readiness"],
        skillConstellation: "Skill constellation",
      },
      creative: {
        processSteps: ["Discover", "Frame", "Build", "Explain"],
      },
      story: {
        currentChapter: "Current chapter",
        careerGraph: "Career graph",
      },
      recruiter: {
        contactPath: "Contact path",
        recruiterOnly: "Recruiter-only demo view",
        scanTitle: "Recruiter scan in 60 seconds",
        topProof: "Top proof",
        skillClusters: "Skill clusters",
        cvPreview: "CV preview",
        downloadNote: "Demo CV action",
      },
      developer: {
        roles: ["AI Engineer", "Full-stack Developer", "Data Builder", "ML Product Student"],
        eyebrow: "Developer Signature",
        command: "$ prooffolio prove --github --certificates --user-approved",
        featured: "Featured proof-of-work",
        filterLabel: "Project filter",
        proofStates: ["GitHub linked", "Demo ready", "Certificate attached"],
        toolkitTitle: "Technical toolkit",
        timelineTitle: "Build history",
      },
      chronicle: {
        badge: "Career Chronicle",
        title: "A career story with proof attached to each chapter.",
        projectDrawer: "Project evidence drawer",
        openProject: "Open project detail",
        closeProject: "Close project detail",
        chapterProgress: "Chapter progress",
        toolkit: "Toolkit progression",
        summary: "Summary",
        purpose: "Why this matters",
        evidence: "Evidence attached",
      },
    },
  },
  fr: {
    nav: {
      home: "Accueil",
      product: "Produit",
      demo: "Démo live",
      templates: "Modèles",
      pricing: "Offres",
      editor: "Éditeur",
      create: "Commencer avec mes preuves",
      startShort: "Commencer",
      startLabel: "Commencer avec mes preuves",
      language: "Langue",
      primary: "Navigation principale",
      menu: "Menu",
      openMenu: "Ouvrir le menu de navigation",
      closeMenu: "Fermer le menu de navigation",
      skip: "Aller au contenu principal",
    },
    common: {
      preview: "Prévisualiser le modèle",
      useTemplate: "Utiliser ce modèle",
      create: "Commencer avec mes preuves",
      demo: "Explorer une démo live",
      openEditor: "Ouvrir l’éditeur",
      viewTemplates: "Voir les modèles",
      proof: "Preuve vérifiée",
      draft: "Brouillon",
      published: "Publié",
      score: "Score de préparation",
      hosted: "Portfolio hébergé",
      contact: "Contact",
      downloadCv: "Télécharger l’aperçu CV",
      viewProof: "Voir la preuve",
      close: "Fermer",
      all: "Tous",
      section: "Section",
    },
    hero: {
      eyebrow: "PORTFOLIOS CONSTRUITS À PARTIR DE VRAIES PREUVES",
      title: "ProofFolio AI",
      emphasis: "Transformez vos projets\nen preuves qui ouvrent des portes.",
      value:
        "ProofFolio AI rassemble votre CV, GitHub et vos certificats pour créer un portfolio professionnel, vérifiable et validé par vous.",
      trust: ["Bilingue", "Contrôlé par vous", "Hébergé", "Partageable"],
      highlights: ["Sourcé", "Validé par vous", "Prêt recruteur"],
      pipeline: ["CV", "GitHub", "Certificats", "Propositions IA", "Portfolio publié"],
      mockupTitle: "Aperçu prêt pour recruteur",
      mockupSubtitle: "Étudiante IA/data · builder orientée produit",
      cards: [
        { label: "CV", value: "Importé et structuré", icon: "file" },
        { label: "GitHub", value: "Projets liés aux preuves", icon: "github" },
        { label: "Certificats", value: "Preuves attachées", icon: "award" },
      ],
    },
    productStage: {
      principle: "L’IA propose. Vous validez. Les recruteurs font confiance aux preuves.",
      tabs: ["Portfolio", "Preuves", "Recruteur"],
      portfolio: {
        label: "Vue portfolio",
        title: "Maya Chen",
        subtitle: "Ingénieure Frontend · Produits IA/Data",
        availability: "Disponible pour stages et premiers postes",
        stack: ["React", "Next.js", "Python", "Data UX"],
        certificates: "4 certificats attachés",
      },
      evidence: {
        label: "Vue preuves",
        title: "File de preuves approuvées",
        sources: ["Repositories GitHub", "Extraction CV", "Certificats", "Liens de preuve"],
        status: "Validé par vous",
        repository: "38 repositories cartographiés",
      },
      recruiter: {
        label: "Vue recruteur",
        title: "Snapshot recruteur en 60 secondes",
        target: "Rôle cible",
        cv: "Simulation téléchargement CV",
        contact: "Contacter la candidate",
      },
    },
    heroPreview: {
      readinessTitle: "Préparation du portfolio",
      readinessChecks: ["CV importé", "Projets GitHub liés", "Certificats attachés"],
      aiSuggestions: "3 suggestions IA à valider",
      githubActivity: "Activité GitHub",
      certificates: "Certificats",
      validationQueue: "File de validation",
    },
    importEvidence: {
      kicker: "Importer vos preuves",
      title: "Commencez avec des sources que les recruteurs peuvent vérifier.",
      body:
        "ProofFolio est conçu autour d’éléments sourcés : CV, repositories GitHub, certificats, contexte LinkedIn et réalisations ajoutées manuellement.",
      sources: [
        { name: "Importer le CV", detail: "Transformer un CV statique en preuves de profil structurées.", icon: "file" },
        { name: "Connecter GitHub", detail: "Relier les repositories à des cartes preuve-de-travail.", icon: "github" },
        { name: "Ajouter LinkedIn", detail: "Utiliser le contexte professionnel sans publication automatique.", icon: "briefcase" },
        { name: "Importer les certificats", detail: "Attacher les preuves directement aux compétences et projets.", icon: "award" },
        { name: "Ajouter manuellement", detail: "Garder le contrôle sur réalisations, rôles et points forts.", icon: "target" },
      ],
    },
    evidenceBoard: {
      queueTitle: "File de preuves",
      columns: ["Source", "Proposition", "Validation"],
      metrics: ["éléments importés", "suggestions IA", "approbations prêtes"],
    },
    workflow: {
      kicker: "Comment ProofFolio fonctionne",
      title: "Un workflow de validation, pas un portfolio en pilote automatique.",
      body:
        "La plateforme suit une boucle claire : importer les preuves, laisser l’IA les structurer, relire chaque suggestion, puis publier volontairement.",
      steps: [
        { number: "01", title: "Importer vos sources", detail: "CV, GitHub, certificats, contexte LinkedIn et preuves manuelles entrent dans un workspace unique." },
        { number: "02", title: "L’IA structure votre travail", detail: "Projets, compétences, certificats et signaux carrière deviennent des propositions éditables." },
        { number: "03", title: "Vous validez chaque suggestion", detail: "Rien n’est publié silencieusement. Vous approuvez, éditez ou rejetez chaque élément généré." },
        { number: "04", title: "Publier votre portfolio", detail: "Lancer une URL portfolio sourcée avec des résumés et preuves prêts pour recruteur." },
      ],
    },
    transformation: {
      kicker: "Démo de transformation",
      title: "Des preuves dispersées vers une présence professionnelle cohérente.",
      body:
        "ProofFolio transforme les éléments de carrière isolés en histoire de portfolio structurée, claire et utile au recrutement.",
      beforeTitle: "Avant",
      afterTitle: "Après",
      before: ["CV simple", "Repos GitHub déconnectés", "Certificats non structurés", "Profil étudiant générique"],
      after: ["Portfolio premium hébergé", "Cartes de preuve de travail", "Score de préparation", "Aperçu recruteur", "Insights IA explicables"],
    },
    intelligence: {
      kicker: "Visualisation de l'intelligence IA",
      title: "L’IA propose. L’utilisateur décide ce qui devient public.",
      body:
        "La démo montre des panneaux d’analyse IA simulés, des états de révision et des points d’approbation sans prétendre fournir des services IA en production.",
      inputTitle: "Entrées",
      outputTitle: "Proposition IA",
      reviewTitle: "Révision utilisateur",
      inputs: ["Texte du CV", "README GitHub", "Compétences", "Certificats", "Preuves projet"],
      outputs: ["Carte de compétences", "Score de préparation", "Évolution de carrière", "Descriptions projets", "Recommandation de modèle"],
      labels: ["Preuve", "Force du signal", "Narratif", "Recommandation"],
      approvals: ["Revoir la proposition", "Ajuster le texte", "Approuver pour le portfolio"],
    },
    platform: {
      kicker: "Workflow produit",
      title: "La démo visible reflète le futur système produit.",
      body:
        "La logique produit d’Aya est représentée comme un parcours avec approbation, de la création du compte au portfolio public, aux analytics et au contact recruteur.",
      stages: [
        { name: "Compte et onboarding", detail: "Choisir un objectif de profil, confirmer la langue et démarrer un espace brouillon." },
        { name: "Connecter les preuves", detail: "Importer CV, repositories GitHub et certificats dans une file de révision unique." },
        { name: "Propositions IA", detail: "ProofFolio suggère résumés, signaux de compétences et récits projet à approuver." },
        { name: "Personnaliser et prévisualiser", detail: "Choisir un modèle, ajuster la typographie, comparer desktop/mobile puis publier volontairement." },
        { name: "Recruteur et analytics", detail: "Partager une URL publique, suivre l’intérêt et garder les notifications dans la boucle produit." },
      ],
    },
    templateShowcase: {
      kicker: "Galerie de modèles",
      title: "Sept modèles, sept façons de raconter un parcours.",
      body:
        "Chaque modèle change le rythme de mise en page, la typographie, le mouvement et l’ambiance pour s’adapter au candidat.",
      directions: [
        { name: "Développeur", detail: "Portfolios riches en preuves pour builders, repositories et systèmes livrés.", template: "developer-signature" },
        { name: "Data / IA", detail: "Preuves structurées pour modèles, notebooks, dashboards et progression.", template: "career-chronicle" },
        { name: "Créatif", detail: "Cas d’étude visuels pour designers d’interface et creative technologists.", template: "creative-grid" },
      ],
    },
    proof: {
      kicker: "Preuves de travail et intelligence GitHub",
      title: "Des preuves, pas des promesses.",
      body:
        "ProofFolio rend la couche de confiance visible : projets liés à GitHub, certificats vérifiés, contenu IA validé par l’utilisateur et éléments de portfolio sourcés.",
      stats: [
        ["12", "projets analysés"],
        ["6", "certificats vérifiés"],
        ["4", "thèmes carrière"],
        ["91", "score portfolio"],
      ],
      projects: [
        { name: "Atlas UI Systems", signal: "Design system · 18 composants réutilisables", proof: "Storybook, notes accessibilité, changelog" },
        { name: "ModelOps Notes", signal: "Workflow IA · prototype local", proof: "README, table de benchmark, captures démo" },
        { name: "Campus Connect", signal: "Produit full-stack · services étudiants", proof: "Docs API, journal de déploiement, notes de test" },
      ],
    },
    career: {
      kicker: "Évolution de carrière",
      title: "Une timeline vivante montre la progression du profil.",
      body:
        "La démo cartographie la dynamique des compétences dans le temps et la transforme en prochaine action concrète.",
      skills: [
        ["Frontend", "92"],
        ["Backend", "76"],
        ["IA", "68"],
        ["Cloud", "63"],
        ["Data", "58"],
      ],
      recommendation:
        "Priorité recommandée : publier deux cas d’étude d’interfaces assistées par IA et ajouter des preuves de déploiement pour l’axe cloud.",
    },
    recruiter: {
      kicker: "Aperçu recruteur",
      title: "Une vue concentrée pour évaluer rapidement.",
      summary:
        "Candidate avec une forte qualité d’interface produit, des preuves d’implémentation crédibles et une direction claire autour des outils IA.",
      target: "Rôle cible",
      role: "Ingénieure Frontend · Interfaces produit IA",
      availability: "Disponible pour stages et premiers postes",
      skills: ["React", "Design systems", "TypeScript", "Workflows IA", "Accessibilité"],
      contact: "Contacter la candidate",
    },
    plans: {
      kicker: "Aperçu des offres",
      title: "Des offres claires pour chaque etape du portfolio.",
      body:
        "Le modèle reste simple : explorer gratuitement, progresser comme étudiant, ou débloquer une présence professionnelle complète.",
      monthly: "Mensuel",
      yearly: "Annuel",
      billingLabel: "Période de facturation",
      tableTitle: "Comparatif des fonctionnalités",
      feature: "Fonctionnalité",
      disclaimer: "Les tarifs sont présentés à titre d’aperçu. Les paiements et la facturation ne sont pas activés dans cette démo.",
      tiers: [
        {
          id: "free",
          name: "Free",
          monthlyPrice: "0 $",
          yearlyPrice: "0 $",
          description: "Découvrez l’essentiel et publiez votre premier portfolio.",
          cta: "Commencer gratuitement",
        },
        {
          id: "student",
          name: "Student",
          monthlyPrice: "5 $ / mois",
          yearlyPrice: "48 $ / an",
          badge: "Le plus populaire",
          description: "Construisez un profil plus solide pour les stages, PFE et premières opportunités.",
          cta: "Choisir Student",
        },
        {
          id: "vip",
          name: "VIP",
          monthlyPrice: "12 $ / mois",
          yearlyPrice: "108 $ / an",
          badge: "Présence professionnelle complète",
          description: "Pour les créateurs et professionnels ambitieux qui veulent l’expérience ProofFolio complète.",
          cta: "Découvrir VIP",
        },
      ],
      comparison: [
        ["Modèles", "1", "3", "7"],
        ["Projets", "3", "10", "Illimité"],
        ["URL publique du portfolio", "Inclus", "Inclus", "Inclus"],
        ["Import GitHub", "Manuel seulement", "Synchronisation basique", "Synchronisation complète"],
        ["Mises à jour GitHub automatiques", "Non inclus", "Limité", "Inclus"],
        ["Analyse CV", "Basique", "Complète", "Complète + comparaison de l’évolution du profil"],
        ["Certificats", "2", "10", "Illimité"],
        ["Couleurs et polices", "Limité", "Avancé", "Personnalisation complète"],
        ["Analytics du portfolio", "Non inclus", "Basique", "Complet"],
        ["Insights carrière", "Basique", "Complet", "Avancé"],
        ["Retirer la marque ProofFolio", "Non inclus", "Non inclus", "Inclus"],
        ["Domaine personnalisé", "Non inclus", "Non inclus", "Fonction VIP bientôt disponible"],
        ["Modèle Recruiter Focus", "Non inclus", "Non inclus", "Inclus"],
        ["Modèle Developer Signature", "Non inclus", "Aperçu Student", "Inclus"],
        ["Modèle Career Chronicle", "Non inclus", "Non inclus", "Inclus"],
      ],
    },
    finalCta: {
      title: "Votre prochain portfolio ne doit pas juste être beau.",
      body: "Il doit prouver ce que vous savez faire, avec des sources que les recruteurs comprennent vite.",
      cta: "Commencer avec mes preuves",
    },
    footer: {
      product: "Démo produit",
      templates: "Modèles",
      note:
        "ProofFolio AI inclut maintenant une fondation Supabase V3 pour l’authentification, les preuves privées et les projets manuels. IA, import GitHub, publication et paiements restent différés.",
    },
    demo: {
      kicker: "Démo produit live",
      title: "Un portfolio exemple complet généré depuis des preuves étudiantes réalistes.",
      body:
        "Cette route montre comment le dashboard, le score de préparation et l’aperçu public fonctionnent pendant que l’onboarding V3 gère la collecte réelle de preuves séparément.",
      tabs: ["Portfolio", "Preuves", "Préparation"],
      candidate: "Maya Chen",
      headline: "Ingénieure frontend orientée produit, créatrice d’outils d’apprentissage assistés par IA.",
      location: "Paris · Ouverte au remote",
      highlights: ["4 démos soignées livrées", "Checklist accessibilité maintenue", "Décisions produit documentées clairement"],
    },
    editor: {
      kicker: "Éditeur de portfolio",
      title: "Façonnez le brouillon sauvegardé derrière l’aperçu.",
      body: "Votre brouillon, vos preuves approuvées et vos préférences visuelles restent réunis dans un espace privé.",
      workspaceTitle: "Construisez le portfolio à partir de contenus fondés sur des preuves.",
      workspaceBody: "Modifiez l’identité, les projets approuvés, la structure des preuves et le système visuel sans transformer les fichiers privés en liens publics.",
      status: "Enregistré dans l’espace",
      evidenceReady: "Brouillon fondé sur des preuves",
      approvedEvidence: "preuves approuvées",
      portfolioId: "ID portfolio",
      publishState: "Brouillon privé uniquement",
      undo: "Annuler",
      redo: "Rétablir",
      mobilePreview: "Aperçu mobile",
      desktopPreview: "Aperçu desktop",
      persistence: {
        ready: "Espace privé connecté",
        readyBody: "Les modifications sont enregistrées dans votre brouillon Supabase, détenu par votre compte.",
        preview: "Espace d’aperçu",
        previewBody: "Aucun portfolio sauvegardé n’est chargé. Les changements restent visuels et ne sont pas présentés comme une persistance backend.",
      },
      unavailable: {
        setup_required: {
          title: "La persistance du portfolio n’est pas configurée.",
          body: "Cet identifiant ne peut pas être chargé tant que l’environnement Supabase et la migration de l’éditeur ne sont pas disponibles.",
        },
        denied: {
          title: "Ce portfolio n’est pas accessible.",
          body: "Le brouillon n’existe pas ou appartient à un autre compte. ProofFolio ne révèle aucun détail de propriété.",
        },
        error: {
          title: "L’espace éditeur n’a pas pu être chargé.",
          body: "Vérifiez que la migration de l’éditeur persistant est appliquée, puis revenez depuis le passage de l’onboarding preuves.",
        },
      },
      panels: {
        identity: "Identité",
        projects: "Projets",
        evidence: "Preuves et certificats",
        structure: "Structure du portfolio",
        appearance: "Apparence",
        motion: "Mouvement avancé",
      },
      panelDescriptions: {
        identity: "Titre du portfolio et accroche professionnelle",
        projects: "Projets manuels approuvés et liens de preuve",
        evidence: "Sources privées et état de relecture",
        structure: "Visibilité et ordre de lecture des sections",
        appearance: "Modèle, couleur, typographie et densité",
        motion: "Mouvements accessibles dans l’aperçu",
      },
      fields: {
        portfolioTitle: "Titre du portfolio",
        headline: "Accroche professionnelle",
        projectTitle: "Titre du projet",
        summary: "Résumé du projet",
        technologies: "Technologies",
        repositoryUrl: "URL du repository",
        liveDemoUrl: "URL de la démo live",
      },
      saveStates: {
        preview: "Aperçu uniquement",
        unsaved: "Modifications non enregistrées",
        saving: "Enregistrement...",
        saved: "Enregistré",
        failed: "Échec de l’enregistrement",
      },
      actions: {
        saveNow: "Enregistrer maintenant",
        saveProject: "Enregistrer le projet",
        moveUp: "Monter",
        moveDown: "Descendre",
        returnToOnboarding: "Revenir à l’onboarding preuves",
      },
      recovery: {
        title: "Texte local non enregistré détecté",
        body: "Une récupération locale contient du texte de ce portfolio qui n’a pas été confirmé par le serveur.",
        restore: "Restaurer le texte",
        dismiss: "Ignorer la récupération",
      },
      evidence: {
        privateNotice: "Les fichiers de preuve restent privés. Cet espace affiche les noms et métadonnées des sources, jamais une URL Storage non authentifiée.",
        approved: "Approuvé pour l’aperçu",
        privateOnly: "Source privée uniquement",
      },
      structure: {
        sections: {
          projects: "Projets",
          evidence: "Preuves",
          certificates: "Certificats",
        },
      },
      sourceBadges: {
        cv: "CV",
        certificate: "Certificat",
        manualProject: "Projet manuel",
        github: "GitHub - bientôt",
      },
      preview: {
        label: "Aperçu du portfolio",
        viewport: "Format de l’aperçu",
        privateDraft: "Aperçu du brouillon privé",
        structureLabel: "Sections du portfolio",
        headlineFallback: "Ajoutez une accroche professionnelle dans Identité.",
        projectsTitle: "Projets sélectionnés",
        evidenceTitle: "Profil fondé sur des preuves",
        certificatesTitle: "Certificats",
        noApprovedProjects: "Aucun projet approuvé n’est prêt pour l’aperçu.",
        noApprovedEvidence: "Aucune source approuvée n’est prête pour cette section.",
        approvedOnly: "Preuves approuvées uniquement",
        approvedSources: "sources approuvées",
        projectCount: "projets",
        repository: "Repository",
        liveDemo: "Démo live",
      },
      emptyStates: {
        projectsTitle: "Aucun projet approuvé",
        projectsBody: "Approuvez une suggestion de projet manuel avant de la modifier comme contenu prêt pour le portfolio.",
        evidenceTitle: "Aucune preuve enregistrée",
        evidenceBody: "Ajoutez un CV privé, un certificat ou un projet manuel dans l’espace de preuves.",
      },
      controls: {
        template: "Modèle",
        color: "Couleur d'accent",
        typography: "Typographie",
        layout: "Mise en page",
        projects: "Affichage projets",
        spacing: "Espacement",
        animation: "Niveau d'animation",
      },
      options: {
        typography: ["Editoriale", "Technique", "Compacte"],
        layout: ["Narratif", "Grille", "Snapshot"],
        projects: ["Cas d’étude", "Cartes de preuve", "Flux repository"],
        spacing: ["Compact", "Équilibré", "Aérien"],
        animation: ["Réduit", "Raffiné", "Expressif"],
      },
      empty: "Aucun projet sélectionné",
      loading: "Actualisation de l'aperçu",
    },
    auth: {
      kicker: "Accès fondé sur les preuves",
      signInTitle: "Reprenez votre espace de preuves.",
      signInBody: "Connectez-vous pour continuer l’onboarding sauvegardé, relire les preuves et préparer le brouillon éditeur.",
      signUpTitle: "Créez le compte qui possède vos preuves.",
      signUpBody: "Démarrez avec un brouillon privé, puis ajoutez CV, certificats et projets manuels.",
      formTitle: "Accès sécurisé au portfolio",
      email: "Adresse e-mail",
      emailPlaceholder: "vous@example.com",
      password: "Mot de passe",
      passwordPlaceholder: "Au moins 6 caractères",
      signInAction: "Se connecter",
      signUpAction: "Créer un compte",
      signOut: "Se déconnecter",
      loading: "Vérification de l’accès...",
      needAccount: "Nouveau sur ProofFolio ?",
      haveAccount: "Vous avez déjà un compte ?",
      createAccount: "Créer un compte",
      backToSignIn: "Se connecter plutôt",
      proofPoints: ["Stockage privé des preuves", "Brouillons appartenant à l’utilisateur", "Aucune fausse promesse IA"],
    },
    onboarding: {
      workspace: "Espace preuves",
      kicker: "Espace guidé de construction par preuves",
      title: "Commencez par les preuves, puis façonnez le portfolio.",
      body:
        "Cette fondation V3 sauvegarde de vrais brouillons, fichiers et projets manuels avant de transmettre le modèle choisi à l’éditeur.",
      resumeTitle: "Reprendre votre brouillon de preuves",
      resumeBody: "Un brouillon sauvegardé attend avec ses preuves privées, ses décisions de relecture et sa progression modèle.",
      resumeDraft: "Reprendre le brouillon",
      startNewDraft: "Commencer un nouveau brouillon",
      progressTitle: "Progression du brouillon",
      progress: {
        sourcesAdded: "Sources ajoutées",
        uploadsCompleted: "Imports terminés",
        projectsAdded: "Projets ajoutés",
        suggestionsApproved: "Suggestions approuvées",
        templateSelected: "Modèle sélectionné",
      },
      progressStates: {
        done: "Terminé",
        pending: "En attente",
      },
      stepEyebrow: "Étape 1",
      uploadEyebrow: "Collecte des preuves",
      reviewEyebrow: "Relecture prototype",
      templateEyebrow: "Recommandation de modèle",
      summaryEyebrow: "Passage à l’éditeur",
      steps: {
        sources: { label: "Sources", detail: "Choisir d’où viendront les preuves." },
        upload: { label: "Preuves", detail: "Importer des PDF ou ajouter un projet manuel." },
        review: { label: "Relecture", detail: "Approuver, éditer ou rejeter les suggestions prototype." },
        template: { label: "Modèle", detail: "Choisir l’expérience portfolio adaptée." },
        summary: { label: "Passage", detail: "Ouvrir le brouillon éditeur fondé sur les preuves." },
      },
      connectedStatus: "Persistance protégée active",
      connectedDetail: "Votre brouillon, vos preuves et vos décisions de relecture sont sauvegardés dans Supabase.",
      previewStatus: "Persistance bloquée",
      persistenceBlocked: "Connectez-vous avec Supabase configuré pour sauvegarder les preuves. Cet aperçu local ne crée pas de compte connecté.",
      persistenceDisabled: "Persistance désactivée",
      honestyNotice: "Vos fichiers restent privés. L’analyse automatique du CV et l’import GitHub arrivent prochainement.",
      sourcesTitle: "Sélectionnez les sources de preuves pour ce portfolio.",
      sourcesBody: "Choisissez ce que vous voulez ajouter en premier. GitHub est visible comme future intégration, mais il n’est pas actif dans ce sprint.",
      sources: {
        cv: "CV",
        cvDetail: "Importer un CV PDF privé sans prétendre à une analyse automatique.",
        certificate: "Certificats",
        certificateDetail: "Stocker les documents de preuve en privé et les attacher au brouillon.",
        manualProject: "Projet manuel",
        manualDetail: "Décrire vous-même un vrai projet, sa stack et ses liens de preuve.",
        github: "GitHub - Bientôt",
        githubDetail: "L’import de repositories est différé ; aucun OAuth n’est implémenté.",
      },
      comingSoon: "Bientôt",
      saved: "sauvegardé",
      ready: "Prêt",
      sourceStates: {
        notAdded: "Non ajouté",
        uploading: "Import en cours",
        savedPrivately: "Sauvegardé en privé",
        needsAttention: "À vérifier",
      },
      uploadTitle: "Ajoutez les éléments de preuve.",
      uploadBody: "Les PDF vont dans un stockage privé. Les projets manuels sont sauvegardés comme preuves et brouillons projet.",
      uploadCv: "Importer le CV",
      uploadCvDetail: "PDF uniquement. Le fichier reste privé et n’est pas encore analysé.",
      uploadCertificate: "Importer un certificat",
      uploadCertificateDetail: "Attacher un certificat PDF au bucket privé de preuves.",
      githubDeferred: "L’import GitHub, OAuth et l’analyse de repository sont volontairement différés.",
      manualProjectTitle: "Ajouter un projet manuel",
      manualProjectBody: "Rédigez vous-même la preuve projet pour garder le premier brouillon honnête.",
      saveManualProject: "Sauvegarder le projet manuel",
      savedEvidence: "Preuves sauvegardées",
      noEvidence: "Aucune preuve sauvegardée pour l’instant.",
      evidenceListTitle: "Coffre de preuves privées",
      removeEvidence: "Supprimer la preuve",
      confirmRemoval: "Confirmer la suppression",
      confirmRemoveBody: "Cela supprime la preuve sauvegardée et invalide les suggestions prototype liées à ce brouillon.",
      removeNow: "Supprimer maintenant",
      fields: {
        projectTitle: "Titre du projet",
        summary: "Résumé court",
        technologies: "Technologies",
        repositoryUrl: "URL du repository",
        liveDemoUrl: "URL de démo live",
        proposalTitle: "Titre de proposition",
        proposalSummary: "Résumé de proposition",
      },
      placeholders: {
        projectTitle: "Atlas UI Systems",
        summary: "Ce que vous avez construit, pourquoi c’est utile et quelles preuves existent.",
        technologies: "React, TypeScript, Supabase",
      },
      validation: {
        projectTitle: "Ajoutez un titre de projet avant de sauvegarder.",
        projectSummary: "Ajoutez un résumé court avant de sauvegarder.",
      },
      reviewTitle: "Relisez les suggestions de brouillon prototype.",
      reviewBody:
        "Ces suggestions déterministes viennent des titres de preuves sauvegardées et des projets manuels. Ce n’est pas une analyse IA.",
      prototypeLabel: "Suggestion de brouillon prototype",
      proofContext: "Contexte de preuve",
      evidenceBacked: "Fondée sur les preuves, car cette suggestion est liée à une preuve sauvegardée dans votre brouillon privé.",
      activeSuggestions: "File de relecture",
      rejectedAuditTitle: "Audit des rejets",
      rejectedAuditBody: "Les suggestions rejetées restent ici pour la traçabilité et sont exclues du résumé portfolio.",
      editSuggestion: "Modifier la suggestion",
      approvedEvidence: "Preuves approuvées",
      noSuggestions: "Ajoutez d’abord des preuves pour générer des suggestions de brouillon prototype.",
      approve: "Approuver",
      edit: "Modifier",
      reject: "Rejeter",
      saving: "Sauvegarde...",
      reviewStates: {
        pending: "En attente",
        approved: "Approuvé",
        edited: "Modifié",
        rejected: "Rejeté",
      },
      sourceBadges: {
        cv: "CV",
        certificate: "Certificat",
        manualProject: "Projet manuel",
        github: "GitHub - bientôt",
      },
      templateTitle: "Choisissez l’expérience portfolio.",
      templateBody: "ProofFolio recommande exactement trois modèles pour ce premier passage fondé sur les preuves.",
      templateReasons: {
        "developer-signature": "Idéal pour les projets techniques, la stack visible et la preuve de travail.",
        "dark-tech": "Idéal lorsque les preuves évoquent IA, data, systèmes ou une identité technique très signalée.",
        "recruiter-focus": "Idéal pour une preuve professionnelle concise et une lecture recruteur rapide.",
      },
      selected: "Sélectionné",
      templateSelectedStatus: "Modèle sélectionné",
      summaryTitle: "Votre brouillon fondé sur des preuves est prêt.",
      summaryBody: "L’éditeur reçoit le vrai ID portfolio, le modèle choisi et l’état de relecture sans prétendre que la publication existe.",
      portfolioDraft: "Brouillon portfolio",
      editorReadyTitle: "Brouillon fondé sur des preuves",
      editorReadyBody: "Ouvrir l’éditeur avec le modèle sauvegardé et le nombre de preuves approuvées.",
      continueEditor: "Continuer vers l’éditeur",
      openPreviewEditor: "Ouvrir l’éditeur aperçu",
      back: "Retour",
      next: "Suivant",
    },
    portfolio: {
      name: "Maya Chen",
      initials: "MC",
      headline: "Étudiante IA/data qui construit des interfaces produit accessibles et des outils d’apprentissage riches en preuves.",
      role: "Développeuse interfaces produit IA",
      targetRole: "Ingénieure Frontend · Produits IA/Data",
      location: "Paris · Ouverte au remote",
      availability: "Disponible pour PFE, stages et premiers rôles en product engineering",
      email: "maya.chen.demo@prooffolio.local",
      summary:
        "Profil fictif pour les démos ProofFolio : solide pratique React, sens du storytelling data et réflexe de documenter les preuves derrière chaque projet.",
      metrics: [
        ["91", "Préparation"],
        ["38", "Repos cartographiés"],
        ["6", "Certificats"],
        ["12", "Projets"],
      ],
      projects: [
        {
          name: "Atlas UI Systems",
          category: "Frontend",
          signal: "Design system · 18 composants réutilisables",
          proof: "Storybook, notes accessibilité, changelog",
          impact: "+42 % de vitesse sur les prototypes",
          detail: "Construction d’une bibliothèque de composants pilotée par tokens pour produits SaaS étudiants, avec états clavier et patterns responsive.",
        },
        {
          name: "ModelOps Notes",
          category: "IA",
          signal: "Workflow IA local · dashboard de comparaison",
          proof: "README, table de benchmark, captures d’évaluation",
          impact: "6 exécutions modèle documentées",
          detail: "Création d’un carnet d’expériences local-first qui explique prompts, latence et qualité de sortie pour projets étudiants.",
        },
        {
          name: "Campus Connect",
          category: "Full-stack",
          signal: "Plateforme services étudiants · API + dashboard",
          proof: "Docs API, journal de déploiement, plan de test",
          impact: "4 workflows principaux livrés",
          detail: "Conception et implémentation d’un flux de services campus avec dashboards par rôle et signalement clair.",
        },
        {
          name: "Insight Lens",
          category: "Data",
          signal: "Story analytics · tendances de préparation",
          proof: "Specs graphiques, dictionnaire data, notes QA",
          impact: "9 signaux carrière visualisés",
          detail: "Cartographie de la croissance projets, certificats et compétences dans un graphe lisible pour améliorer le profil.",
        },
      ],
      skills: [
        ["React", "92"],
        ["TypeScript", "86"],
        ["Next.js", "82"],
        ["Python", "74"],
        ["Data UX", "79"],
        ["Accessibilité", "88"],
      ],
      certificates: ["Google UX Foundations", "Meta Front-End Developer", "IBM Data Fundamentals", "Scrimba React Advanced"],
      timeline: [
        {
          chapter: "Fondations",
          date: "2023",
          title: "Construire une base frontend fiable",
          detail: "Passage d’exercices UI isolés à des interfaces React documentées avec checklist accessibilité.",
          learned: "Des composants lisibles, des états clavier et des design tokens rendent les preuves plus fiables.",
        },
        {
          chapter: "Premiers projets",
          date: "2024",
          title: "Livrer des démos produit étudiantes",
          detail: "Transformation de workflows campus en prototypes full-stack avec documentation API et notes de déploiement.",
          learned: "Les recruteurs comprennent plus vite quand les résultats et preuves accompagnent les liens code.",
        },
        {
          chapter: "Transition IA",
          date: "2025",
          title: "Ajouter IA et storytelling data",
          detail: "Association de la qualité d’interface à des expériences IA locales, benchmarks et décisions explicables.",
          learned: "La sortie IA doit être approuvée, éditée et reliée à des preuves avant d’être publique.",
        },
        {
          chapter: "Focus actuel",
          date: "2026",
          title: "Se positionner en product engineering IA",
          detail: "Affinage des cas d’étude autour de la pensée produit, de la qualité d’interface et des preuves mesurables.",
          learned: "Un portfolio vivant doit montrer la progression, pas seulement une liste statique.",
        },
      ],
      scanSteps: ["Résumé fit", "Qualité des preuves", "Top projets", "Match compétences", "Contact"],
      filters: ["Tous", "Frontend", "IA", "Full-stack", "Data"],
    },
    templates: {
      "minimal-executive": {
        name: "Minimal Executive",
        tag: "Élégant, calme, orienté senior.",
        motion: "Reveals presque statiques, survols raffinés et transitions discrètes.",
        profile: "Un portfolio précis pour candidats techniques proches du business.",
      },
      "dark-tech": {
        name: "Dark Tech",
        tag: "Profondeur, lumière bleue, énergie développeur.",
        motion: "Profondeur ambiante, cartes projet interactives et rythme GitHub.",
        profile: "Un portfolio technique premium pour builders avec preuves solides.",
      },
      "creative-grid": {
        name: "Creative Grid",
        tag: "Visuel, modulaire, toujours professionnel.",
        motion: "Mouvement de galerie fluide, expansion projet et rythme image.",
        profile: "Un portfolio design-forward pour creative technologists et designers UI.",
      },
      "story-journey": {
        name: "Story Journey",
        tag: "Narration de carrière avec élan.",
        motion: "Jalons liés au scroll, reveals progressifs et timeline centrale.",
        profile: "Un portfolio narratif pour candidats en progression, reconversion ou pivot.",
      },
      "recruiter-focus": {
        name: "Recruiter Focus",
        tag: "Scan rapide, clarté maximale.",
        motion: "Score retenu, actions nettes et accès rapide aux preuves.",
        profile: "Un portfolio concis pour recruteurs qui veulent fit, preuve et contact vite.",
      },
      "developer-signature": {
        name: "Developer Signature",
        tag: "Identité technique et preuves solides.",
        motion: "Rôles typewriter, filtres projet, profondeur au survol et clusters toolkit.",
        profile: "Un portfolio développeur pour ingénieurs IA, builders full-stack et profils data.",
      },
      "career-chronicle": {
        name: "Career Chronicle",
        tag: "Un récit de carrière chronologique premium.",
        motion: "Chapitres liés au scroll, modal projet et progression toolkit mesurée.",
        profile: "Un récit professionnel pour étudiants et juniors qui doivent expliquer leur progression.",
      },
    },
    templateUi: {
      nav: {
        intro: "Intro",
        projects: "Projets",
        skills: "Compétences",
        evidence: "Preuves",
        contact: "Contact",
        proof: "Preuves",
        signals: "Signaux",
        gallery: "Galerie",
        process: "Processus",
        timeline: "Parcours",
        growth: "Progression",
        summary: "Résumé",
        scan: "Scan",
        cv: "CV",
        home: "Accueil",
        work: "Travail",
        toolkit: "Toolkit",
        journey: "Parcours",
        proofLab: "Lab preuves",
        portrait: "Portrait",
        chronology: "Chronologie",
        chapters: "Chapitres",
      },
      minimal: {
        selectedWork: "Travaux sélectionnés",
        skillSignal: "Signal compétences",
      },
      dark: {
        flagship: "Dark Tech signature",
        roles: ["Ingénieure IA", "Développeuse full-stack", "Builder data"],
        assurance: ["Preuves verrouillées", "IA relue", "Validé par vous"],
        activity: "Activité simulée en direct",
        command: "$ proofolio scan --preuves --validation-obligatoire",
        signals: ["Repositories", "Projets livrés", "Commits", "Certificats", "Préparation profil"],
        skillConstellation: "Constellation de compétences",
      },
      creative: {
        processSteps: ["Explorer", "Cadrer", "Construire", "Expliquer"],
      },
      story: {
        currentChapter: "Chapitre actuel",
        careerGraph: "Graphe de carrière",
      },
      recruiter: {
        contactPath: "Chemin de contact",
        recruiterOnly: "Vue démo réservée recruteur",
        scanTitle: "Scan recruteur en 60 secondes",
        topProof: "Preuves clés",
        skillClusters: "Groupes de compétences",
        cvPreview: "Aperçu CV",
        downloadNote: "Action CV simulée",
      },
      developer: {
        roles: ["Ingénieure IA", "Développeuse full-stack", "Builder data", "Étudiante produit ML"],
        eyebrow: "Developer Signature",
        command: "$ prooffolio prove --github --certificats --validation-utilisateur",
        featured: "Preuve de travail mise en avant",
        filterLabel: "Filtre projet",
        proofStates: ["GitHub lié", "Démo prête", "Certificat attaché"],
        toolkitTitle: "Toolkit technique",
        timelineTitle: "Historique de construction",
      },
      chronicle: {
        badge: "Career Chronicle",
        title: "Un récit de carrière avec une preuve attachée à chaque chapitre.",
        projectDrawer: "Panneau de preuves projet",
        openProject: "Ouvrir le détail projet",
        closeProject: "Fermer le détail projet",
        chapterProgress: "Progression des chapitres",
        toolkit: "Progression toolkit",
        summary: "Résumé",
        purpose: "Pourquoi c’est important",
        evidence: "Preuve attachée",
      },
    },
  },
} as const;

export type Copy = (typeof copy)["en"];

export function getCopy(locale: Locale): Copy {
  return copy[locale] as Copy;
}
