import {
  Award,
  BadgeCheck,
  BriefcaseBusiness,
  Code2,
  FileText,
  FolderGit,
  GraduationCap,
  LayoutDashboard,
  Palette,
  Route,
  ScanSearch,
  Sparkles,
  Target,
  UserCheck,
} from "lucide-react";

export const locales = ["en", "fr"] as const;
export type Locale = (typeof locales)[number];
export type Direction = "ltr" | "rtl";

export const localeMeta: Record<Locale, { label: string; name: string; dir: Direction }> = {
  en: { label: "EN", name: "English", dir: "ltr" },
  fr: { label: "FR", name: "Français", dir: "ltr" },
};

export const futureLocaleMeta = {
  ar: { label: "AR", name: "Arabic", dir: "rtl" as Direction },
};

export const templateIds = [
  "minimal-executive",
  "dark-tech",
  "creative-grid",
  "story-journey",
  "recruiter-focus",
] as const;

export type TemplateId = (typeof templateIds)[number];

export const templateMeta: Record<
  TemplateId,
  {
    icon: typeof BriefcaseBusiness;
    className: string;
    accent: string;
    previewClass: string;
  }
> = {
  "minimal-executive": {
    icon: BriefcaseBusiness,
    className: "template-minimal",
    accent: "#315dff",
    previewClass: "bg-[#f8f4ed] text-[#172033]",
  },
  "dark-tech": {
    icon: Code2,
    className: "template-dark",
    accent: "#4da3ff",
    previewClass: "bg-[#071021] text-white",
  },
  "creative-grid": {
    icon: Palette,
    className: "template-creative",
    accent: "#ff7a66",
    previewClass: "bg-[#fff8ed] text-[#151926]",
  },
  "story-journey": {
    icon: Route,
    className: "template-story",
    accent: "#67e8a5",
    previewClass: "bg-[#141014] text-[#fff9f2]",
  },
  "recruiter-focus": {
    icon: UserCheck,
    className: "template-recruiter",
    accent: "#0f766e",
    previewClass: "bg-[#f7f9fc] text-[#172033]",
  },
};

export const icons = {
  award: Award,
  badge: BadgeCheck,
  briefcase: BriefcaseBusiness,
  code: Code2,
  file: FileText,
  github: FolderGit,
  graduate: GraduationCap,
  dashboard: LayoutDashboard,
  scan: ScanSearch,
  sparkles: Sparkles,
  target: Target,
};

export const copy = {
  en: {
    nav: {
      product: "Product",
      demo: "Live demo",
      templates: "Templates",
      pricing: "Plans",
      editor: "Editor",
      create: "Create your portfolio",
      language: "Language",
    },
    common: {
      preview: "Preview template",
      useTemplate: "Use this template",
      create: "Create your portfolio",
      demo: "Explore a live demo",
      openEditor: "Open editor",
      viewTemplates: "View templates",
      proof: "Verified proof",
      draft: "Draft",
      published: "Published",
      score: "Readiness score",
      hosted: "Hosted portfolio",
      contact: "Contact",
      downloadCv: "Download CV preview",
      viewProof: "View proof",
      close: "Close",
      all: "All",
      section: "Section",
    },
    hero: {
      eyebrow: "PORTFOLIOS BUILT FROM REAL EVIDENCE",
      title: "ProofFolio AI",
      emphasis: "Turn your projects into proof that opens doors.",
      value:
        "ProofFolio AI brings together your CV, GitHub and certificates to create a professional, verifiable portfolio that you validate before it goes public.",
      trust: ["Bilingual", "Controlled by you", "Hosted", "Shareable"],
      highlights: ["Source-backed", "User-validated", "Recruiter-ready"],
      pipeline: ["CV", "GitHub", "Certificates", "AI proposals", "Published portfolio"],
      mockupTitle: "Recruiter-ready snapshot",
      mockupSubtitle: "AI/data student · product-minded builder",
      cards: [
        { label: "CV", value: "Imported and structured", icon: "file" },
        { label: "GitHub", value: "Projects linked to proof", icon: "github" },
        { label: "Certificates", value: "Evidence attached", icon: "award" },
      ],
    },
    heroPreview: {
      readinessTitle: "Portfolio readiness",
      readinessChecks: ["CV imported", "GitHub projects linked", "Certificates attached"],
      aiSuggestions: "3 AI suggestions awaiting approval",
      githubActivity: "GitHub activity",
      certificates: "Certificates",
      validationQueue: "Validation queue",
    },
    importEvidence: {
      kicker: "Import your evidence",
      title: "Start with sources recruiters can actually trust.",
      body:
        "ProofFolio is designed around source-backed material: CV details, GitHub repositories, certificates, LinkedIn context and manual achievements.",
      sources: [
        { name: "Upload CV", detail: "Turn a static resume into structured profile evidence.", icon: "file" },
        { name: "Connect GitHub", detail: "Map repositories to proof-of-work project cards.", icon: "github" },
        { name: "Add LinkedIn", detail: "Use professional context without publishing blindly.", icon: "briefcase" },
        { name: "Upload certificates", detail: "Attach proof directly to skills and projects.", icon: "award" },
        { name: "Add manually", detail: "Keep control over achievements, roles and highlights.", icon: "target" },
      ],
    },
    evidenceBoard: {
      queueTitle: "Evidence queue",
      columns: ["Source", "Proposal", "Validation"],
      metrics: ["items imported", "AI suggestions", "ready approvals"],
    },
    workflow: {
      kicker: "How ProofFolio works",
      title: "A validation workflow, not an autopilot portfolio.",
      body:
        "The platform is built around a clear loop: import evidence, let AI structure it, review every suggestion, then publish intentionally.",
      steps: [
        { number: "01", title: "Import your sources", detail: "CV, GitHub, certificates, LinkedIn context and manual proof enter one workspace." },
        { number: "02", title: "AI structures your work", detail: "Projects, skills, certificates and career signals become editable proposals." },
        { number: "03", title: "You validate each suggestion", detail: "Nothing is published silently. You approve, edit or reject every generated item." },
        { number: "04", title: "Publish your portfolio", detail: "Launch a source-backed portfolio URL with recruiter-ready summaries and evidence." },
      ],
    },
    transformation: {
      kicker: "Transformation demo",
      title: "From scattered proof to a coherent professional presence.",
      body:
        "ProofFolio turns disconnected career material into a structured portfolio story with evidence, clarity and hiring context.",
      beforeTitle: "Before",
      afterTitle: "After",
      before: ["Plain CV document", "Disconnected GitHub repositories", "Unstructured certificates", "Generic student profile"],
      after: ["Premium hosted portfolio", "Proof-of-work cards", "Readiness score", "Recruiter snapshot", "Explainable AI insights"],
    },
    intelligence: {
      kicker: "AI intelligence visualization",
      title: "AI proposes. The user decides what becomes public.",
      body:
        "The demo shows simulated AI analysis panels, review states and approval checkpoints without claiming production AI services.",
      inputTitle: "Input",
      outputTitle: "AI proposal",
      reviewTitle: "User review",
      inputs: ["CV text", "GitHub README", "Skills", "Certificates", "Project evidence"],
      outputs: ["Skill map", "Readiness score", "Career evolution", "Project descriptions", "Template recommendation"],
      labels: ["Evidence", "Signal strength", "Narrative", "Recommendation"],
      approvals: ["Review proposal", "Edit language", "Approve for portfolio"],
    },
    platform: {
      kicker: "Product workflow",
      title: "The visible demo mirrors the future product system.",
      body:
        "Aya's product logic is represented as an approval-based journey from account setup to public portfolio, analytics and recruiter contact.",
      stages: [
        { name: "Account and onboarding", detail: "Choose a profile goal, confirm language and start with a draft workspace." },
        { name: "Connect evidence", detail: "Import CV content, GitHub repositories and certificates into one review queue." },
        { name: "AI proposals", detail: "ProofFolio suggests summaries, skill signals and project stories for user approval." },
        { name: "Customize and preview", detail: "Select a template, tune typography, switch desktop/mobile previews and publish intentionally." },
        { name: "Recruiter and analytics", detail: "Share a public URL, track interest and keep notifications visible in the product loop." },
      ],
    },
    templateShowcase: {
      kicker: "Template showcase",
      title: "Five templates, five different professional stories.",
      body:
        "Each template changes layout rhythm, typography, motion and mood so the portfolio fits the candidate rather than forcing everyone into one skin.",
      directions: [
        { name: "Developer", detail: "Proof-heavy portfolios for builders, repositories and shipped systems.", template: "dark-tech" },
        { name: "Data / AI", detail: "Structured evidence for models, notebooks, dashboards and learning curves.", template: "story-journey" },
        { name: "Creative", detail: "Visual case studies for interface designers and creative technologists.", template: "creative-grid" },
      ],
    },
    proof: {
      kicker: "Proof, not promises",
      title: "Every strong claim needs a visible source.",
      body:
        "ProofFolio makes the trust layer visible: GitHub-linked projects, verified certificates, user-approved AI content and source-backed portfolio elements.",
      stats: [
        ["12", "projects analyzed"],
        ["6", "verified certificates"],
        ["4", "career themes"],
        ["91", "portfolio score"],
      ],
      projects: [
        { name: "Atlas UI Systems", signal: "Design system · 18 reusable components", proof: "Storybook, accessibility notes, release changelog" },
        { name: "ModelOps Notes", signal: "AI workflow · local inference prototype", proof: "README, benchmark table, demo screenshots" },
        { name: "Campus Connect", signal: "Full-stack product · student services", proof: "API docs, deployment log, testing notes" },
      ],
    },
    career: {
      kicker: "Career evolution",
      title: "A living timeline shows where the profile is growing.",
      body:
        "The product demo maps skill momentum over time and turns it into a practical next-step recommendation.",
      skills: [
        ["Frontend", "92"],
        ["Backend", "76"],
        ["AI", "68"],
        ["Cloud", "63"],
        ["Data", "58"],
      ],
      recommendation:
        "Recommended focus: publish two AI-assisted interface case studies and add deployment evidence for the cloud track.",
    },
    recruiter: {
      kicker: "Recruiter snapshot",
      title: "A focused view for fast evaluation.",
      summary:
        "Candidate with strong product UI craft, credible implementation evidence and a clear AI tooling direction.",
      target: "Target role",
      role: "Frontend Engineer · AI Product Interfaces",
      availability: "Available for internships and junior roles",
      skills: ["React", "Design systems", "TypeScript", "AI workflows", "Accessibility"],
      contact: "Contact candidate",
    },
    plans: {
      kicker: "Pricing preview",
      title: "Clear plans for every stage of the portfolio journey.",
      body:
        "The model stays simple: explore for free, grow as a student, or unlock the complete professional presence.",
      monthly: "Monthly",
      yearly: "Yearly",
      billingLabel: "Billing period",
      tableTitle: "Feature comparison",
      feature: "Feature",
      disclaimer: "Pricing is a product preview. Payments and billing are not enabled in this demo.",
      tiers: [
        {
          id: "free",
          name: "Free",
          monthlyPrice: "$0",
          yearlyPrice: "$0",
          description: "Explore the essentials and publish your first portfolio.",
          cta: "Start free",
        },
        {
          id: "student",
          name: "Student",
          monthlyPrice: "$5 / month",
          yearlyPrice: "$48 / year",
          badge: "Most popular",
          description: "Build a stronger profile for internships, PFE, and early career opportunities.",
          cta: "Choose Student",
        },
        {
          id: "vip",
          name: "VIP",
          monthlyPrice: "$12 / month",
          yearlyPrice: "$108 / year",
          badge: "Full professional presence",
          description: "For ambitious creators and professionals who want the complete ProofFolio experience.",
          cta: "Explore VIP",
        },
      ],
      comparison: [
        ["Templates", "1", "3", "5"],
        ["Projects", "3", "10", "Unlimited"],
        ["Public portfolio URL", "Included", "Included", "Included"],
        ["GitHub import", "Manual only", "Basic sync", "Full sync"],
        ["GitHub auto-updates", "Not included", "Limited", "Included"],
        ["CV analysis", "Basic", "Full", "Full + profile evolution comparison"],
        ["Certificates", "2", "10", "Unlimited"],
        ["Colors and fonts", "Limited", "Advanced", "Full customization"],
        ["Portfolio analytics", "Not included", "Basic", "Full"],
        ["Career insights", "Basic", "Full", "Advanced"],
        ["Remove ProofFolio branding", "Not included", "Not included", "Included"],
        ["Custom domain", "Not included", "Not included", "VIP feature coming soon"],
        ["Recruiter Focus template", "Not included", "Not included", "Included"],
      ],
    },
    finalCta: {
      title: "Your next portfolio should not just look good.",
      body: "It should prove what you can do, with sources recruiters can understand quickly.",
      cta: "Create your portfolio for free",
    },
    footer: {
      product: "Product demo",
      templates: "Templates",
      note:
        "ProofFolio AI is presented here as a bilingual UI demo using local mock data only. No external AI, GitHub connection, payments or persistence are active.",
    },
    demo: {
      kicker: "Live product demo",
      title: "A complete sample portfolio generated from realistic student evidence.",
      body:
        "This route shows how the dashboard, readiness score and public portfolio preview work together before any real backend is added.",
      tabs: ["Portfolio", "Evidence", "Readiness"],
      candidate: "Maya Chen",
      headline: "Product-minded frontend engineer building AI-assisted learning tools.",
      location: "Paris · Remote friendly",
      highlights: ["Shipped 4 polished demos", "Maintains an accessibility checklist", "Documents product decisions clearly"],
    },
    editor: {
      kicker: "Portfolio editor",
      title: "Tune the profile and watch the preview respond instantly.",
      body: "The editor is local-state only for this first pass, with a state model prepared for undo and redo.",
      status: "Saved locally",
      publishState: "Published preview ready",
      undo: "Undo",
      redo: "Redo",
      mobilePreview: "Mobile preview",
      desktopPreview: "Desktop preview",
      controls: {
        template: "Template",
        color: "Accent color",
        typography: "Typography",
        layout: "Layout",
        projects: "Project display",
        spacing: "Spacing",
        animation: "Animation level",
      },
      options: {
        typography: ["Editorial", "Technical", "Compact"],
        layout: ["Narrative", "Grid", "Snapshot"],
        projects: ["Case studies", "Evidence cards", "Repository feed"],
        spacing: ["Compact", "Balanced", "Airy"],
        animation: ["Reduced", "Refined", "Expressive"],
      },
      empty: "No project selected",
      loading: "Refreshing preview",
    },
    portfolio: {
      name: "Maya Chen",
      initials: "MC",
      headline: "AI/data student building accessible product interfaces and evidence-rich learning tools.",
      role: "AI Product Interface Developer",
      targetRole: "Frontend Engineer · AI/Data Products",
      location: "Paris · Remote friendly",
      availability: "Available for PFE, internships and junior product engineering roles",
      email: "maya.chen.demo@prooffolio.local",
      summary:
        "A fictional portfolio profile for ProofFolio demos: strong React craft, data storytelling instincts, and a habit of documenting proof behind each project.",
      metrics: [
        ["91", "Readiness"],
        ["38", "Repos mapped"],
        ["6", "Certificates"],
        ["12", "Projects"],
      ],
      projects: [
        {
          name: "Atlas UI Systems",
          category: "Frontend",
          signal: "Design system · 18 reusable components",
          proof: "Storybook coverage, accessibility notes, release changelog",
          impact: "+42% faster prototype handoff",
          detail: "Built a token-led component library for student SaaS products with keyboard states and responsive patterns.",
        },
        {
          name: "ModelOps Notes",
          category: "AI",
          signal: "Local AI workflow · model comparison dashboard",
          proof: "README, benchmark table, evaluation screenshots",
          impact: "6 model runs documented",
          detail: "Created a local-first experiment notebook that explains prompts, latency and output quality for student projects.",
        },
        {
          name: "Campus Connect",
          category: "Full-stack",
          signal: "Student services platform · API + dashboard",
          proof: "API docs, deployment log, test plan",
          impact: "4 core workflows shipped",
          detail: "Designed and implemented a campus services flow with role-aware dashboards and clean issue reporting.",
        },
        {
          name: "Insight Lens",
          category: "Data",
          signal: "Analytics story · portfolio readiness trends",
          proof: "Chart specs, data dictionary, QA notes",
          impact: "9 career signals visualized",
          detail: "Mapped project, certificate and skill growth into a readable readiness graph for profile improvement.",
        },
      ],
      skills: [
        ["React", "92"],
        ["TypeScript", "86"],
        ["Next.js", "82"],
        ["Python", "74"],
        ["Data UX", "79"],
        ["Accessibility", "88"],
      ],
      certificates: ["Google UX Foundations", "Meta Front-End Developer", "IBM Data Fundamentals", "Scrimba React Advanced"],
      timeline: [
        {
          chapter: "Foundations",
          date: "2023",
          title: "Built the first reliable frontend base",
          detail: "Moved from isolated UI exercises to documented React interfaces with accessibility checklists.",
          learned: "Readable components, keyboard states and design tokens make portfolio proof easier to trust.",
        },
        {
          chapter: "First Projects",
          date: "2024",
          title: "Shipped student-facing product demos",
          detail: "Turned campus workflows into full-stack prototypes with API documentation and deployment notes.",
          learned: "Recruiters understand projects faster when outcomes and proof sit next to the code links.",
        },
        {
          chapter: "AI Transition",
          date: "2025",
          title: "Added AI and data storytelling",
          detail: "Started pairing interface craft with local AI experiments, benchmarks and explainable decisions.",
          learned: "AI output needs user approval, editing and traceable evidence before it belongs in a public profile.",
        },
        {
          chapter: "Current Focus",
          date: "2026",
          title: "Positioning for AI product engineering",
          detail: "Refining case studies around product thinking, interface quality and measurable proof-of-work.",
          learned: "A living portfolio should show growth, not just a static list of past work.",
        },
      ],
      scanSteps: ["Fit summary", "Proof quality", "Top projects", "Skill match", "Contact path"],
      filters: ["All", "Frontend", "AI", "Full-stack", "Data"],
    },
    templates: {
      "minimal-executive": {
        name: "Minimal Executive",
        tag: "Elegant, calm, senior-facing.",
        motion: "Nearly static reveals, refined hover states and understated section transitions.",
        profile: "A precise portfolio for business-oriented technical candidates.",
      },
      "dark-tech": {
        name: "Dark Tech",
        tag: "Depth, blue lighting, developer energy.",
        motion: "Ambient depth, interactive project cards and GitHub activity rhythm.",
        profile: "A premium technical portfolio for builders with strong implementation evidence.",
      },
      "creative-grid": {
        name: "Creative Grid",
        tag: "Visual, modular, still professional.",
        motion: "Smooth gallery movement, project expansion and image-led rhythm.",
        profile: "A design-forward portfolio for creative technologists and interface designers.",
      },
      "story-journey": {
        name: "Story Journey",
        tag: "Career narrative with momentum.",
        motion: "Scroll-linked milestones, progressive reveals and timeline emphasis.",
        profile: "A storytelling portfolio for candidates changing levels, domains or roles.",
      },
      "recruiter-focus": {
        name: "Recruiter Focus",
        tag: "Fast scanning, high clarity.",
        motion: "Restrained scoring, clear actions and quick evidence access.",
        profile: "A concise portfolio for recruiters who need fit, proof and contact paths quickly.",
      },
    },
    templateUi: {
      nav: {
        intro: "Intro",
        projects: "Projects",
        skills: "Skills",
        evidence: "Evidence",
        contact: "Contact",
        proof: "Proof",
        signals: "Signals",
        gallery: "Gallery",
        process: "Process",
        timeline: "Timeline",
        growth: "Growth",
        summary: "Summary",
        scan: "Scan",
        cv: "CV",
      },
      minimal: {
        selectedWork: "Selected work",
        skillSignal: "Skill signal",
      },
      dark: {
        flagship: "Dark Tech flagship",
        roles: ["AI Engineer", "Full-Stack Developer", "Data Builder"],
        assurance: ["Evidence locked", "AI reviewed", "User approved"],
        activity: "Live-looking activity",
        command: "$ proofolio scan --evidence --approval-required",
        signals: ["Repositories", "Shipped projects", "Commits", "Certificates", "Profile readiness"],
        skillConstellation: "Skill constellation",
      },
      creative: {
        processSteps: ["Discover", "Frame", "Build", "Explain"],
      },
      story: {
        currentChapter: "Current chapter",
        careerGraph: "Career graph",
      },
      recruiter: {
        contactPath: "Contact path",
        scanTitle: "Recruiter scan in 60 seconds",
        topProof: "Top proof",
        skillClusters: "Skill clusters",
        cvPreview: "CV preview",
      },
    },
  },
  fr: {
    nav: {
      product: "Produit",
      demo: "Démo live",
      templates: "Modèles",
      pricing: "Offres",
      editor: "Éditeur",
      create: "Créer votre portfolio",
      language: "Langue",
    },
    common: {
      preview: "Prévisualiser le modèle",
      useTemplate: "Utiliser ce modèle",
      create: "Créer votre portfolio",
      demo: "Explorer une démo live",
      openEditor: "Ouvrir l’éditeur",
      viewTemplates: "Voir les modèles",
      proof: "Preuve vérifiée",
      draft: "Brouillon",
      published: "Publié",
      score: "Score de préparation",
      hosted: "Portfolio hébergé",
      contact: "Contact",
      downloadCv: "Télécharger l’aperçu CV",
      viewProof: "Voir la preuve",
      close: "Fermer",
      all: "Tous",
      section: "Section",
    },
    hero: {
      eyebrow: "PORTFOLIOS CONSTRUITS À PARTIR DE VRAIES PREUVES",
      title: "ProofFolio AI",
      emphasis: "Transformez vos projets en preuves qui ouvrent des portes.",
      value:
        "ProofFolio AI rassemble votre CV, GitHub et vos certificats pour créer un portfolio professionnel, vérifiable et validé par vous.",
      trust: ["Bilingue", "Contrôlé par vous", "Hébergé", "Partageable"],
      highlights: ["Sourcé", "Validé par vous", "Prêt recruteur"],
      pipeline: ["CV", "GitHub", "Certificats", "Propositions IA", "Portfolio publié"],
      mockupTitle: "Aperçu prêt pour recruteur",
      mockupSubtitle: "Étudiante IA/data · builder orientée produit",
      cards: [
        { label: "CV", value: "Importé et structuré", icon: "file" },
        { label: "GitHub", value: "Projets liés aux preuves", icon: "github" },
        { label: "Certificats", value: "Preuves attachées", icon: "award" },
      ],
    },
    heroPreview: {
      readinessTitle: "Préparation du portfolio",
      readinessChecks: ["CV importé", "Projets GitHub liés", "Certificats attachés"],
      aiSuggestions: "3 suggestions IA à valider",
      githubActivity: "Activité GitHub",
      certificates: "Certificats",
      validationQueue: "File de validation",
    },
    importEvidence: {
      kicker: "Importer vos preuves",
      title: "Commencez avec des sources que les recruteurs peuvent vérifier.",
      body:
        "ProofFolio est conçu autour d’éléments sourcés : CV, repositories GitHub, certificats, contexte LinkedIn et réalisations ajoutées manuellement.",
      sources: [
        { name: "Importer le CV", detail: "Transformer un CV statique en preuves de profil structurées.", icon: "file" },
        { name: "Connecter GitHub", detail: "Relier les repositories à des cartes preuve-de-travail.", icon: "github" },
        { name: "Ajouter LinkedIn", detail: "Utiliser le contexte professionnel sans publication automatique.", icon: "briefcase" },
        { name: "Importer les certificats", detail: "Attacher les preuves directement aux compétences et projets.", icon: "award" },
        { name: "Ajouter manuellement", detail: "Garder le contrôle sur réalisations, rôles et points forts.", icon: "target" },
      ],
    },
    evidenceBoard: {
      queueTitle: "File de preuves",
      columns: ["Source", "Proposition", "Validation"],
      metrics: ["éléments importés", "suggestions IA", "approbations prêtes"],
    },
    workflow: {
      kicker: "Comment ProofFolio fonctionne",
      title: "Un workflow de validation, pas un portfolio en pilote automatique.",
      body:
        "La plateforme suit une boucle claire : importer les preuves, laisser l’IA les structurer, relire chaque suggestion, puis publier volontairement.",
      steps: [
        { number: "01", title: "Importer vos sources", detail: "CV, GitHub, certificats, contexte LinkedIn et preuves manuelles entrent dans un workspace unique." },
        { number: "02", title: "L’IA structure votre travail", detail: "Projets, compétences, certificats et signaux carrière deviennent des propositions éditables." },
        { number: "03", title: "Vous validez chaque suggestion", detail: "Rien n’est publié silencieusement. Vous approuvez, éditez ou rejetez chaque élément généré." },
        { number: "04", title: "Publier votre portfolio", detail: "Lancer une URL portfolio sourcée avec des résumés et preuves prêts pour recruteur." },
      ],
    },
    transformation: {
      kicker: "Démo de transformation",
      title: "Des preuves dispersées vers une présence professionnelle cohérente.",
      body:
        "ProofFolio transforme les éléments de carrière isolés en histoire de portfolio structurée, claire et utile au recrutement.",
      beforeTitle: "Avant",
      afterTitle: "Après",
      before: ["CV simple", "Repos GitHub déconnectés", "Certificats non structurés", "Profil étudiant générique"],
      after: ["Portfolio premium hébergé", "Cartes de preuve de travail", "Score de préparation", "Aperçu recruteur", "Insights IA explicables"],
    },
    intelligence: {
      kicker: "Visualisation de l'intelligence IA",
      title: "L’IA propose. L’utilisateur décide ce qui devient public.",
      body:
        "La démo montre des panneaux d’analyse IA simulés, des états de révision et des points d’approbation sans prétendre fournir des services IA en production.",
      inputTitle: "Entrées",
      outputTitle: "Proposition IA",
      reviewTitle: "Révision utilisateur",
      inputs: ["Texte du CV", "README GitHub", "Compétences", "Certificats", "Preuves projet"],
      outputs: ["Carte de compétences", "Score de préparation", "Évolution de carrière", "Descriptions projets", "Recommandation de modèle"],
      labels: ["Preuve", "Force du signal", "Narratif", "Recommandation"],
      approvals: ["Revoir la proposition", "Ajuster le texte", "Approuver pour le portfolio"],
    },
    platform: {
      kicker: "Workflow produit",
      title: "La démo visible reflète le futur système produit.",
      body:
        "La logique produit d’Aya est représentée comme un parcours avec approbation, de la création du compte au portfolio public, aux analytics et au contact recruteur.",
      stages: [
        { name: "Compte et onboarding", detail: "Choisir un objectif de profil, confirmer la langue et démarrer un espace brouillon." },
        { name: "Connecter les preuves", detail: "Importer CV, repositories GitHub et certificats dans une file de révision unique." },
        { name: "Propositions IA", detail: "ProofFolio suggère résumés, signaux de compétences et récits projet à approuver." },
        { name: "Personnaliser et prévisualiser", detail: "Choisir un modèle, ajuster la typographie, comparer desktop/mobile puis publier volontairement." },
        { name: "Recruteur et analytics", detail: "Partager une URL publique, suivre l’intérêt et garder les notifications dans la boucle produit." },
      ],
    },
    templateShowcase: {
      kicker: "Galerie de modèles",
      title: "Cinq modèles, cinq façons de raconter un parcours.",
      body:
        "Chaque modèle change le rythme de mise en page, la typographie, le mouvement et l’ambiance pour s’adapter au candidat.",
      directions: [
        { name: "Développeur", detail: "Portfolios riches en preuves pour builders, repositories et systèmes livrés.", template: "dark-tech" },
        { name: "Data / IA", detail: "Preuves structurées pour modèles, notebooks, dashboards et progression.", template: "story-journey" },
        { name: "Créatif", detail: "Cas d’étude visuels pour designers d’interface et creative technologists.", template: "creative-grid" },
      ],
    },
    proof: {
      kicker: "Preuves de travail et intelligence GitHub",
      title: "Des preuves, pas des promesses.",
      body:
        "ProofFolio rend la couche de confiance visible : projets liés à GitHub, certificats vérifiés, contenu IA validé par l’utilisateur et éléments de portfolio sourcés.",
      stats: [
        ["12", "projets analysés"],
        ["6", "certificats vérifiés"],
        ["4", "thèmes carrière"],
        ["91", "score portfolio"],
      ],
      projects: [
        { name: "Atlas UI Systems", signal: "Design system · 18 composants réutilisables", proof: "Storybook, notes accessibilité, changelog" },
        { name: "ModelOps Notes", signal: "Workflow IA · prototype local", proof: "README, table de benchmark, captures démo" },
        { name: "Campus Connect", signal: "Produit full-stack · services étudiants", proof: "Docs API, journal de déploiement, notes de test" },
      ],
    },
    career: {
      kicker: "Évolution de carrière",
      title: "Une timeline vivante montre la progression du profil.",
      body:
        "La démo cartographie la dynamique des compétences dans le temps et la transforme en prochaine action concrète.",
      skills: [
        ["Frontend", "92"],
        ["Backend", "76"],
        ["IA", "68"],
        ["Cloud", "63"],
        ["Data", "58"],
      ],
      recommendation:
        "Priorité recommandée : publier deux cas d’étude d’interfaces assistées par IA et ajouter des preuves de déploiement pour l’axe cloud.",
    },
    recruiter: {
      kicker: "Aperçu recruteur",
      title: "Une vue concentrée pour évaluer rapidement.",
      summary:
        "Candidate avec une forte qualité d’interface produit, des preuves d’implémentation crédibles et une direction claire autour des outils IA.",
      target: "Rôle cible",
      role: "Ingénieure Frontend · Interfaces produit IA",
      availability: "Disponible pour stages et premiers postes",
      skills: ["React", "Design systems", "TypeScript", "Workflows IA", "Accessibilité"],
      contact: "Contacter la candidate",
    },
    plans: {
      kicker: "Aperçu des offres",
      title: "Des offres claires pour chaque etape du portfolio.",
      body:
        "Le modèle reste simple : explorer gratuitement, progresser comme étudiant, ou débloquer une présence professionnelle complète.",
      monthly: "Mensuel",
      yearly: "Annuel",
      billingLabel: "Période de facturation",
      tableTitle: "Comparatif des fonctionnalités",
      feature: "Fonctionnalité",
      disclaimer: "Les tarifs sont présentés à titre d’aperçu. Les paiements et la facturation ne sont pas activés dans cette démo.",
      tiers: [
        {
          id: "free",
          name: "Free",
          monthlyPrice: "0 $",
          yearlyPrice: "0 $",
          description: "Découvrez l’essentiel et publiez votre premier portfolio.",
          cta: "Commencer gratuitement",
        },
        {
          id: "student",
          name: "Student",
          monthlyPrice: "5 $ / mois",
          yearlyPrice: "48 $ / an",
          badge: "Le plus populaire",
          description: "Construisez un profil plus solide pour les stages, PFE et premières opportunités.",
          cta: "Choisir Student",
        },
        {
          id: "vip",
          name: "VIP",
          monthlyPrice: "12 $ / mois",
          yearlyPrice: "108 $ / an",
          badge: "Présence professionnelle complète",
          description: "Pour les créateurs et professionnels ambitieux qui veulent l’expérience ProofFolio complète.",
          cta: "Découvrir VIP",
        },
      ],
      comparison: [
        ["Modèles", "1", "3", "5"],
        ["Projets", "3", "10", "Illimité"],
        ["URL publique du portfolio", "Inclus", "Inclus", "Inclus"],
        ["Import GitHub", "Manuel seulement", "Synchronisation basique", "Synchronisation complète"],
        ["Mises à jour GitHub automatiques", "Non inclus", "Limité", "Inclus"],
        ["Analyse CV", "Basique", "Complète", "Complète + comparaison de l’évolution du profil"],
        ["Certificats", "2", "10", "Illimité"],
        ["Couleurs et polices", "Limité", "Avancé", "Personnalisation complète"],
        ["Analytics du portfolio", "Non inclus", "Basique", "Complet"],
        ["Insights carrière", "Basique", "Complet", "Avancé"],
        ["Retirer la marque ProofFolio", "Non inclus", "Non inclus", "Inclus"],
        ["Domaine personnalisé", "Non inclus", "Non inclus", "Fonction VIP bientôt disponible"],
        ["Modèle Recruiter Focus", "Non inclus", "Non inclus", "Inclus"],
      ],
    },
    finalCta: {
      title: "Votre prochain portfolio ne doit pas juste être beau.",
      body: "Il doit prouver ce que vous savez faire, avec des sources que les recruteurs comprennent vite.",
      cta: "Créer mon portfolio gratuitement",
    },
    footer: {
      product: "Démo produit",
      templates: "Modèles",
      note:
        "ProofFolio AI est présentée ici comme démo UI bilingue avec données locales fictives. Aucune IA externe, connexion GitHub, paiement ou persistance n’est active.",
    },
    demo: {
      kicker: "Démo produit live",
      title: "Un portfolio exemple complet généré depuis des preuves étudiantes réalistes.",
      body:
        "Cette route montre comment le dashboard, le score de préparation et l’aperçu public fonctionnent ensemble avant tout backend réel.",
      tabs: ["Portfolio", "Preuves", "Préparation"],
      candidate: "Maya Chen",
      headline: "Ingénieure frontend orientée produit, créatrice d’outils d’apprentissage assistés par IA.",
      location: "Paris · Ouverte au remote",
      highlights: ["4 démos soignées livrées", "Checklist accessibilité maintenue", "Décisions produit documentées clairement"],
    },
    editor: {
      kicker: "Éditeur de portfolio",
      title: "Ajustez le profil et observez l’aperçu répondre instantanément.",
      body: "L’éditeur utilise seulement l’état local dans ce premier passage, avec une structure prête pour annuler et rétablir.",
      status: "Enregistré localement",
      publishState: "Aperçu publié prêt",
      undo: "Annuler",
      redo: "Rétablir",
      mobilePreview: "Aperçu mobile",
      desktopPreview: "Aperçu desktop",
      controls: {
        template: "Modèle",
        color: "Couleur d'accent",
        typography: "Typographie",
        layout: "Mise en page",
        projects: "Affichage projets",
        spacing: "Espacement",
        animation: "Niveau d'animation",
      },
      options: {
        typography: ["Editoriale", "Technique", "Compacte"],
        layout: ["Narratif", "Grille", "Snapshot"],
        projects: ["Cas d'etude", "Cartes de preuve", "Flux repository"],
        spacing: ["Compact", "Équilibré", "Aérien"],
        animation: ["Réduit", "Raffiné", "Expressif"],
      },
      empty: "Aucun projet sélectionné",
      loading: "Actualisation de l'aperçu",
    },
    portfolio: {
      name: "Maya Chen",
      initials: "MC",
      headline: "Étudiante IA/data qui construit des interfaces produit accessibles et des outils d’apprentissage riches en preuves.",
      role: "Développeuse interfaces produit IA",
      targetRole: "Ingénieure Frontend · Produits IA/Data",
      location: "Paris · Ouverte au remote",
      availability: "Disponible pour PFE, stages et premiers rôles en product engineering",
      email: "maya.chen.demo@prooffolio.local",
      summary:
        "Profil fictif pour les démos ProofFolio : solide pratique React, sens du storytelling data et réflexe de documenter les preuves derrière chaque projet.",
      metrics: [
        ["91", "Préparation"],
        ["38", "Repos cartographiés"],
        ["6", "Certificats"],
        ["12", "Projets"],
      ],
      projects: [
        {
          name: "Atlas UI Systems",
          category: "Frontend",
          signal: "Design system · 18 composants réutilisables",
          proof: "Storybook, notes accessibilité, changelog",
          impact: "+42 % de vitesse sur les prototypes",
          detail: "Construction d’une bibliothèque de composants pilotée par tokens pour produits SaaS étudiants, avec états clavier et patterns responsive.",
        },
        {
          name: "ModelOps Notes",
          category: "IA",
          signal: "Workflow IA local · dashboard de comparaison",
          proof: "README, table de benchmark, captures d’évaluation",
          impact: "6 exécutions modèle documentées",
          detail: "Création d’un carnet d’expériences local-first qui explique prompts, latence et qualité de sortie pour projets étudiants.",
        },
        {
          name: "Campus Connect",
          category: "Full-stack",
          signal: "Plateforme services étudiants · API + dashboard",
          proof: "Docs API, journal de déploiement, plan de test",
          impact: "4 workflows principaux livrés",
          detail: "Conception et implémentation d’un flux de services campus avec dashboards par rôle et signalement clair.",
        },
        {
          name: "Insight Lens",
          category: "Data",
          signal: "Story analytics · tendances de préparation",
          proof: "Specs graphiques, dictionnaire data, notes QA",
          impact: "9 signaux carrière visualisés",
          detail: "Cartographie de la croissance projets, certificats et compétences dans un graphe lisible pour améliorer le profil.",
        },
      ],
      skills: [
        ["React", "92"],
        ["TypeScript", "86"],
        ["Next.js", "82"],
        ["Python", "74"],
        ["Data UX", "79"],
        ["Accessibilité", "88"],
      ],
      certificates: ["Google UX Foundations", "Meta Front-End Developer", "IBM Data Fundamentals", "Scrimba React Advanced"],
      timeline: [
        {
          chapter: "Fondations",
          date: "2023",
          title: "Construire une base frontend fiable",
          detail: "Passage d’exercices UI isolés à des interfaces React documentées avec checklist accessibilité.",
          learned: "Des composants lisibles, des états clavier et des design tokens rendent les preuves plus fiables.",
        },
        {
          chapter: "Premiers projets",
          date: "2024",
          title: "Livrer des démos produit étudiantes",
          detail: "Transformation de workflows campus en prototypes full-stack avec documentation API et notes de déploiement.",
          learned: "Les recruteurs comprennent plus vite quand les résultats et preuves accompagnent les liens code.",
        },
        {
          chapter: "Transition IA",
          date: "2025",
          title: "Ajouter IA et storytelling data",
          detail: "Association de la qualité d’interface à des expériences IA locales, benchmarks et décisions explicables.",
          learned: "La sortie IA doit être approuvée, éditée et reliée à des preuves avant d’être publique.",
        },
        {
          chapter: "Focus actuel",
          date: "2026",
          title: "Se positionner en product engineering IA",
          detail: "Affinage des cas d’étude autour de la pensée produit, de la qualité d’interface et des preuves mesurables.",
          learned: "Un portfolio vivant doit montrer la progression, pas seulement une liste statique.",
        },
      ],
      scanSteps: ["Résumé fit", "Qualité des preuves", "Top projets", "Match compétences", "Contact"],
      filters: ["Tous", "Frontend", "IA", "Full-stack", "Data"],
    },
    templates: {
      "minimal-executive": {
        name: "Minimal Executive",
        tag: "Élégant, calme, orienté senior.",
        motion: "Reveals presque statiques, survols raffinés et transitions discrètes.",
        profile: "Un portfolio précis pour candidats techniques proches du business.",
      },
      "dark-tech": {
        name: "Dark Tech",
        tag: "Profondeur, lumière bleue, énergie développeur.",
        motion: "Profondeur ambiante, cartes projet interactives et rythme GitHub.",
        profile: "Un portfolio technique premium pour builders avec preuves solides.",
      },
      "creative-grid": {
        name: "Creative Grid",
        tag: "Visuel, modulaire, toujours professionnel.",
        motion: "Mouvement de galerie fluide, expansion projet et rythme image.",
        profile: "Un portfolio design-forward pour creative technologists et designers UI.",
      },
      "story-journey": {
        name: "Story Journey",
        tag: "Narration de carrière avec élan.",
        motion: "Jalons liés au scroll, reveals progressifs et timeline centrale.",
        profile: "Un portfolio narratif pour candidats en progression, reconversion ou pivot.",
      },
      "recruiter-focus": {
        name: "Recruiter Focus",
        tag: "Scan rapide, clarté maximale.",
        motion: "Score retenu, actions nettes et accès rapide aux preuves.",
        profile: "Un portfolio concis pour recruteurs qui veulent fit, preuve et contact vite.",
      },
    },
    templateUi: {
      nav: {
        intro: "Intro",
        projects: "Projets",
        skills: "Compétences",
        evidence: "Preuves",
        contact: "Contact",
        proof: "Preuves",
        signals: "Signaux",
        gallery: "Galerie",
        process: "Processus",
        timeline: "Parcours",
        growth: "Progression",
        summary: "Résumé",
        scan: "Scan",
        cv: "CV",
      },
      minimal: {
        selectedWork: "Travaux sélectionnés",
        skillSignal: "Signal compétences",
      },
      dark: {
        flagship: "Dark Tech signature",
        roles: ["Ingénieure IA", "Développeuse full-stack", "Builder data"],
        assurance: ["Preuves verrouillées", "IA relue", "Validé par vous"],
        activity: "Activité simulée en direct",
        command: "$ proofolio scan --preuves --validation-obligatoire",
        signals: ["Repositories", "Projets livrés", "Commits", "Certificats", "Préparation profil"],
        skillConstellation: "Constellation de compétences",
      },
      creative: {
        processSteps: ["Explorer", "Cadrer", "Construire", "Expliquer"],
      },
      story: {
        currentChapter: "Chapitre actuel",
        careerGraph: "Graphe de carrière",
      },
      recruiter: {
        contactPath: "Chemin de contact",
        scanTitle: "Scan recruteur en 60 secondes",
        topProof: "Preuves clés",
        skillClusters: "Groupes de compétences",
        cvPreview: "Aperçu CV",
      },
    },
  },
} as const;

export type Copy = (typeof copy)["en"];

export function getCopy(locale: Locale): Copy {
  return copy[locale] as Copy;
}
